module.exports = [
  {
    idUser: 1,
    title: "Data Base",
    subtitle: "Que es?",
    text: "Es un almacén o bóveda en donde el sistema guarda la información seleccionada por el usuario. Dicha información puede ser almacenada utilizando estructuras definidas, de manera que acceder a la información sea un proceso rápido dentro de la base de datos.",
    img: "https://bs-uploads.toptal.io/blackfish-uploads/components/seo/content/og_image_file/og_image/1275009/0712-Bad_Practices_in_Database_Design_-_Are_You_Making_These_Mistakes_Dan_Social-754bc73011e057dc76e55a44a954e0c3.png",
    subtitleTwo: "Bases de datos estáticas",
    textTwo:
      "Son bases de datos únicamente de lectura, utilizadas principalmente para almacenar datos históricos que posteriormente se pueden utilizar para estudiar el comportamiento de un conjunto de datos a través del tiempo, realizar proyecciones, tomar decisiones y realizar análisis de datos para inteligencia empresarial.",
    subtitleThree: "Bases de datos dinámicas",
    textThree:
      "Son bases de datos donde la información almacenada se modifica con el tiempo, permitiendo operaciones como actualización, borrado y edición de datos, además de las operaciones fundamentales de consulta. Un ejemplo puede ser la base de datos utilizada en un sistema de información de un supermercado.",
  },
  {
    idUser: 1,
    title: "ORM",
    subtitle: "¿Qué es un ORM?",
    text: "Un ORM es un modelo de programación que permite mapear las estructuras de una base de datos relacional (SQL Server, Oracle, MySQL, etc.), en adelante RDBMS (Relational Database Management System), sobre una estructura lógica de entidades con el objeto de simplificar y acelerar el desarrollo de nuestras aplicaciones.",
    img: "https://blog.ensalza.com/wp-content/uploads/orm.jpg",
    subtitleTwo: "El problema",
    textTwo:
      "En la programación orientada a objetos, las tareas de gestión de datos son implementadas generalmente por la manipulación de objetos, los cuales son casi siempre valores no escalares. Para ilustrarlo, considere el ejemplo de una entrada en una libreta de direcciones, que representa a una sola persona con cero o más números telefónicos y cero o más direcciones.",
    subtitleThree: "Implementaciones",
    textThree:
      "Los tipos de bases de datos usados mayoritariamente son las bases de datos SQL, cuya aparición precedió al crecimiento de la programación orientada a objetos en los 1990s. Las bases de datos SQL usan una serie de tablas para organizar datos. Los datos en distintas tablas están asociados a través del uso de restricciones declarativas en lugar de punteros o enlaces explícitos. Los mismos datos que pueden almacenarse en un solo objeto podrían requerir ser almacenados a través de varias tablas.",
  },
  {
    idUser: 2,
    title: "pentesting",
    subtitle: "¿Que es?",
    text: "El Pentesting es un test de penetración que valora los posibles fallos de seguridad informática que puede tener un sistema y qué alcance tienen dichos fallos. Es el resultado de unir dos conceptos: penetration y testing.",
    img: "https://www.ceupe.com/images/easyblog_articles/2329/pentesting.jpg",
    subtitleTwo: "texto descrictivo",
    textTwo: "este es una descripcion de prueba",
    subtitleThree: "texto descrictivo",
    textThree: "este es una descripcion de prueba",
  },
  {
    idUser: 2,
    title: "hacker y cracker",
    subtitle: "Diferencias",
    text: "En su versión positiva, un hacker es un ciberexperto cuya labor es imprescindible para defender no solo las infraestructuras críticas de los países, sino los sistemas de datos de las empresas privadas del mundo entero. Un cracker, en cambio, sería un ciberexperto que emplea su talento cibernético para hacer el mal.",
    img: "https://www.cloudcenterandalucia.es/wp-content/uploads/2022/01/Hacker-vs-Cracker_Cloud-Center-Andaluc%C3%ADa_Principal.png",
    subtitleTwo: "texto descrictivo",
    textTwo: "este es una descripcion de prueba",
    subtitleThree: "texto descrictivo",
    textThree: "este es una descripcion de prueba",
  },
  {
    idUser: 4,
    title: "windows",
    subtitle: "Que es?",
    text: "Windows es el nombre de una familia de distribuciones de software para PC, servidores, sistemas empotrados y antiguamente teléfonos inteligentes desarrollados y vendidos por Microsoft y disponibles para múltiples",
    img: "https://cdn.computerhoy.com/sites/navi.axelspringer.es/public/media/image/2022/10/ultima-actualizacion-windows-10-11-trae-consigo-problemas-red-puedes-solucionarlos-2846589.jpg?tf=3840x",
    subtitleTwo: "texto descrictivo",
    textTwo: "este es una descripcion de prueba",
    subtitleThree: "texto descrictivo",
    textThree: "este es una descripcion de prueba",
  },
  {
    idUser: 4,
    title: "linux",
    subtitle: "Que es?",
    text: "es un sistema operativo (o una familia de sistemas operativos) tipo Unix compuesto por software libre y de código abierto. GNU/Linux surge de las contribuciones de varios proyectos de software, entre los cuales destacan GNU (iniciado por Richard Stallman en 1983) y el kernel Linux (iniciado por Linus Torvalds en 1991).",
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQz-RE0z8IVd5njOpWvPRFSqEf_vEItb9kLMg&usqp=CAU",
    subtitleTwo: "texto descrictivo",
    textTwo: "este es una descripcion de prueba",
    subtitleThree: "texto descrictivo",
    textThree: "este es una descripcion de prueba",
  },
  {
    idUser: 4,
    title: "react native",
    subtitle: "Que es?",
    text: " es un framework JavaScript para crear aplicaciones reales nativas para iOS y Android, basado en la librearía de JavaScript React para la creación de componentes visuales, cambiando el propósito de los mismos para, en lugar de ser ejecutados en navegador, correr directamente sobre las plataformas móviles nativas, en este caso iOS y Andorid.",
    img: "https://www.programaenlinea.net/wp-content/uploads/2020/08/react-native.jpg",
    subtitleTwo: "texto descrictivo",
    textTwo: "este es una descripcion de prueba",
    subtitleThree: "texto descrictivo",
    textThree: "este es una descripcion de prueba",
  },
  {
    idUser: 2,
    title: "Redux",
    subtitle: "Que es?",
    text: "es una librería JavaScript de código abierto para el manejo del estado de las aplicaciones. Es comúnmente usada con otras librerías como React o Angular para la construcción de Interfaces de Usuario.",
    img: "https://digital55.com/wp-content/uploads/2022/01/Cuando_y_por_que_debo_usar_redux_en_mis_proyectos_frontend.jpg",
    subtitleTwo: "texto descrictivo",
    textTwo: "este es una descripcion de prueba",
    subtitleThree: "texto descrictivo",
    textThree: "este es una descripcion de prueba",
  },
  {
    idUser: 2,
    title: "pandas",
    subtitle: "Que es?",
    text: "es una librería de Python especializada en la manipulación y el análisis de datos. Ofrece estructuras de datos y operaciones para manipular tablas numéricas y series temporales, es como el Excel de Python. Es un software libre distribuido bajo la licencia BSD.",
    img: "https://www.datocms-assets.com/14946/1628604937-pandas.png?auto=format&corner-radius=16&fit=crop&h=312&mask=corners&q=45&w=568",
    subtitleTwo: "texto descrictivo",
    textTwo: "este es una descripcion de prueba",
    subtitleThree: "texto descrictivo",
    textThree: "este es una descripcion de prueba",
  },
  {
    idUser: 1,
    title: "NoSQL",
    subtitle: "Que es?",
    text: "El término NoSQL se refiere a tipos de bases de datos no relacionales que almacenan datos en un formato distinto a las tablas relacionales.",
    img: "https://www.scylladb.com/wp-content/uploads/nosql-design-principles-diagram.png",
    subtitleTwo: "texto descrictivo",
    textTwo: "este es una descripcion de prueba",
    subtitleThree: "texto descrictivo",
    textThree: "este es una descripcion de prueba",
  },
];
