module.exports = [
    {
        "title":"Python para todos",
        "description":"This Specialization builds on the success of the Python for Everybody course and will introduce fundamental programming concepts including data structures, networked application program interfaces, and databases, using the Python programming language. In the Capstone Project, you’ll use the technologies learned throughout the Specialization to design and create your own  applications for data retrieval, processing, and visualization.",
        "image":"https://www.freecodecamp.org/news/content/images/2022/02/Banner-10.png",
        "lenguage":"ENGLISH", 
        "price":30,
        "pro":false, 
        "duration":"Aproximadamente 8 meses para completarse, Ritmo sugerido de 3 horas/semana", 
        "content":"This course aims to teach everyone the basics of programming computers using Python. We cover the basics of how one constructs a program from a series of simple instructions in Python.  The course has no pre-requisites and avoids all but the simplest mathematics. Anyone with moderate computer experience should be able to master the materials in this course. This course will cover Chapters 1-5 of the textbook “Python for Everybody”.  Once a student completes this course, they will be ready to take more advanced programming courses. This course covers Python 3.",
        "dificulty":"BASIC",
        "requirement":"Un computador y muchas ganas de aprender",
        "learnTo":["Install Python and write your first program","Describe the basics of the Python programming language","Use variables to store, retrieve and calculate information","Utilize core programming tools such as functions and loops"],
        "studyMethod":"Metodo en como se entregara el curso, importante, es un texto plano, no mas de 255 caracteres",
        "users":[1], 
        "catego":[1]
    },
    {
        "title":"Algorithms, Part I",
        "description":"This course covers the essential information that every serious programmer needs to know about algorithms and data structures, with emphasis on applications and scientific performance analysis of Java implementations. Part I covers elementary data structures, sorting, and searching algorithms. Part II focuses on graph- and string-processing algorithms.",
        "image":"https://www.ucv.edu.mx/wp-content/uploads/2021/11/laptop-gb6b3da8de_1280.png",
        "lenguage":"ENGLISH", 
        "price":19.99,
        "pro":false, 
        "duration":"Aprox. 54 horas para completar", 
        "content":"We begin by describing the desirable properties of hash function and how to implement them in Java, including a fundamental tenet known as the uniform hashing assumption that underlies the potential success of a hashing application. Then, we consider two strategies for implementing hash tables—separate chaining and linear probing. Both strategies yield constant-time performance for search and insert under the uniform hashing assumption.",
        "dificulty":"MEDIUM", 
        "requirement":"basic computer and eager to learn",
        "learnTo":["Data Structure","Algorithms","Java Programming"],
        "studyMethod":"The course is delivered in a zip file",
        "users":[2], 
        "catego":[2]
    },
    {
        "title":"C Programming with Linux",
        "description":"Gain skills in computer engineering - C and Linux. Become a skilled C programmer and start a career in computer engineering.",
        "image":"https://www.profesionalreview.com/wp-content/uploads/2016/05/linux-4.6-ya-disponible.jpg",
        "lenguage":"ENGLISH", 
        "price":44,
        "pro":false, 
        "duration":"Aproximadamente 6 meses para completarse", 
        "content":"In this C Programming with Linux Specialization program of seven short courses, you will learn how to write, read and debug computer programs in the C programming language while also becoming familiar with the Linux operating system.",
        "dificulty":"MEDIUM", 
        "requirement":"basic computer and eager to learn",
        "learnTo":["Data Structure","Algorithms","Java Programming"],
        "studyMethod":"The course is delivered in a zip file",
        "users":[3], 
        "catego":[3]
    },
    {
        "title":"Introduction to C# Programming and Unity",
        "description":"This course is all about starting to learn how to develop video games using the C# programming language and the Unity game engine on Windows or Mac. Why use C# and Unity instead of some other language and game engine? Well, C# is a really good language for learning how to program and then programming professionally. Also, the Unity game engine is very popular with indie game developers; Unity games were downloaded 16,000,000,000 times in 2016! Finally, C# is one of the programming languages you can use in the Unity environment.",
        "image":"https://media.tutellus.com/libraries/88/43/02/01/lib/1643886975505_1.jpg?size=854x493s&ext=jpg",
        "lenguage":"ENGLISH", 
        "price":37,
        "pro":false, 
        "duration":"Aprox. 18 horas para completar", 
        "content":"In this module, you'll learn about the course and get Unity installed and configured. You'll write your first C# console application and your first C# script in Unity.",
        "dificulty":"BASIC", 
        "requirement":"basic computer and eager to learn",
        "learnTo":["Video Game Development","C Sharp (C#) (Programming Language)","Unity (User Interface)","Game Programming"],
        "studyMethod":"The course is delivered in a zip file",
        "users":[4], 
        "catego":[4]
    },
    {
        "title":"HTML, CSS y Javascript para desarrolladores web",
        "description":"Do you realize that the only functionality of a web application that the user directly interacts with is through the web page? Implement it poorly and, to the user, the server-side becomes irrelevant! Today’s user expects a lot out of the web page: it has to load fast, expose the desired service, and be comfortable to view on all devices: from a desktop computers to tablets and mobile phones.",
        "image":"https://www.cursosgis.com/wp-content/uploads/2017/06/lenguajes_1.png",
        "lenguage":"ENGLISH", 
        "price":19.99,
        "pro":false, 
        "duration":"Aprox. 40 horas para completar", 
        "content":"In this module we will learn the basics of HTML5. We'll start with instructional videos on how to set up your development environment, go over HTML5 basics like valid document structure, which elements can be included inside other elements and which can not, discuss the meaning and usefulness of HTML5 semantic tags, and go over essential HTML5 tags.",
        "dificulty":"MEDIUM", 
        "requirement":"basic computer and eager to learn",
        "learnTo":["HTML","JavaScript","Css Frameworks","Cascading Style Sheets (CSS)"],
        "studyMethod":"The course is delivered in a zip file",
        "users":[5], 
        "catego":[5]
    },
    {
        "title":"Desarrollo de aplicaciones web en PHP",
        "description":"In this course, you'll explore the basic structure of a web application, and how a web browser interacts with a web server. You'll be introduced to the request/response cycle, including GET/POST/Redirect. You'll also gain an introductory understanding of Hypertext Markup Language (HTML), as well as the basic syntax and data structures of the PHP language, variables, logic, iteration, arrays, error handling, and superglobal variables, among other elements. An introduction to Cascading Style Sheets (CSS) will allow you to style markup for webpages. ",
        "image":"https://www.qualitydevs.com/wp-content/uploads/2021/05/PHP-Quality-Devs-1-1288x724.jpg",
        "lenguage":"ESPAÑOL", 
        "price":55,
        "pro":false, 
        "duration":"Aprox. 30 horas para completar", 
        "content":"We look at the basic structure of a web application and how a web browser interacts with a web server. We explore the Request-Response Cycle that is the basis of the Hypertext Transfer Protocol (HTTP).",
        "dificulty":"MEDIUM", 
        "requirement":"basic computer and eager to learn",
        "learnTo":["Hypertext Preprocessor (PHP)","HTML","Cascading Style Sheets (CSS)"],
        "studyMethod":"The course is delivered in a zip file",
        "users":[1], 
        "catego":[6]
    },
    {
        "title":"Estructuras de datos y algoritmos",
        "description":"dominar técnicas de programación de algoritmos. Advance your Software Engineering or Data Science Career by Learning Algorithms through Programming and Puzzle Solving. Ace coding interviews by implementing each algorithmic challenge in this Specialization. Apply the newly-learned algorithmic techniques to real-life problems, such as analyzing a huge social network or sequencing a genome of a deadly pathogen.",
        "image":"https://img-b.udemycdn.com/course/750x422/3654148_572b.jpg",
        "lenguage":"ENGLISH", 
        "price":25,
        "pro":false, 
        "duration":"Aproximadamente 8 meses para completarse", 
        "content":"Computer science legend Donald Knuth once said “I don’t understand things unless I try to program them.” We also believe that the best way to learn an algorithm is to program it. However, many excellent books and online courses on algorithms, that excel in introducing algorithmic ideas, have not yet succeeded in teaching you how to implement algorithms, the crucial computer science skill that you have to master at your next job interview. We tried to fill this gap by forming a diverse team of instructors that includes world-leading experts in theoretical and applied algorithms at UCSD (Daniel Kane, Alexander Kulikov, and Pavel Pevzner) and a former software engineer at Google (Neil Rhodes).",
        "dificulty":"ADVANCED",
        "requirement":"basic computer and eager to learn",
        "learnTo":["Apply the newly learned algorithms to solve real-world challenges: navigating in a Big Network  or assembling a genome of a deadly pathogen from millions of short substrings of its DNA.","If you decide to venture beyond Algorithms 101, try to solve more complex programming challenges (flows in networks, linear programming, streaming algorithms, etc.) and complete an equivalent of a graduate course in algorithms!"],
        "studyMethod":"The course is delivered in a zip file",
        "users":[2], 
        "catego":[7]
    },
    {
        "title":"Information Systems",
        "description":"Tecnología de información . Become a better manager of information technology to address business problems",
        "image":"https://s40424.pcdn.co/in/wp-content/uploads/2022/07/info-systems.jpg.optimal.jpg",
        "lenguage":"ENGLISH", 
        "price":19.99,
        "pro":false, 
        "duration":"Aproximadamente 5 meses para completarse", 
        "content":"The first course describes how Information Systems address business problems. This takes the form of an IT alignment model that describes how Information Systems provide capabilities that enable or support organizational strategy. This component also includes an economic analysis of the Information System. ",
        "dificulty":"BASIC", 
        "requirement":"basic computer and eager to learn",
        "learnTo":["Utilize conceptual frameworks to align IT investments with business strategy","Specify business requirements as information system specifications","Assess the fit between business requirements and enterprise systems features","Evaluate technological alternatives for developing the IT infrastructure for the organization"],
        "studyMethod":"The course is delivered in a zip file",
        "users":[3], 
        "catego":[8]
    },
    {
        "title":"Introduction to Cybersecurity Tools & Cyber Attacks",
        "description":"This course gives you the background needed to understand basic Cybersecurity.  You will learn the history of Cybersecurity, types and motives of cyber attacks to further your knowledge of current threats to organizations and individuals.  Key terminology, basic system concepts and tools will be examined as an introduction to the Cybersecurity field.",
        "image":"https://d1m75rqqgidzqn.cloudfront.net/wp-data/2020/09/21141520/iStock-1185245180.jpg",
        "lenguage":"ESPAÑOL", 
        "price":67,
        "pro":false, 
        "duration":"Aprox. 16 horas para completar", 
        "content":"This module will give you a brief overview of the history of cybersecurity. You will also learn key terms and roles in cybersecurity.",
        "dificulty":"MEDIUM", //BASIC ADVANCED
        "requirement":"basic computer and eager to learn",
        "learnTo":["Discuss the evolution of security based on historical events.","List various types of malicious software.","Describe key cybersecurity concepts including the CIA Triad, access management, incident response and common cybersecurity best practices. "],
        "studyMethod":"The course is delivered in a zip file",
        "users":[4], 
        "catego":[9]
    },
    {
        "title":"Using JavaScript, JQuery, and JSON in Django",
        "description":"In this final course, we'll look at the JavaScript language and how it supports the Object-Oriented pattern, with a focus on the unique aspects of JavaScript's approach to OO. We'll provide an introduction to the jQuery library, which is widely used for in-browser manipulation of the Document Object Model (DOM) and event handling. You'll also learn about JavaScript Object Notation (JSON), which is commonly used as a syntax to exchange data between code running on the server (i.e., in Django) and code running in the browser (JavaScript/jQuery).",
        "image":"https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://coursera-course-photos.s3.amazonaws.com/a3/b2fb1ff20c4c0e8b7593d5d6a697fa/dj4e_thumbnail_v4_1.jpg?auto=format%2Ccompress%2C%20enhance&dpr=1&w=265&h=204&q=50&fit=crop",
        "lenguage":"ENGLISH", 
        "price":80,
        "pro":false, 
        "duration":"Aprox. 18 horas para completar", 
        "content":"Explain and give examples of many-to-many relationships in data modeling. Write syntactically correct JavaScript language and demonstrate debugging capabilities. Build objects using JavaScript y Explain basic elements of low-level jQuery",
        "dificulty":"MEDIUM",
        "requirement":"basic computer and eager to learn",
        "learnTo":["Document Object Model (DOM)","Jquery","Many-to-many data modeling","Json","JavaScript"],
        "studyMethod":"The course is delivered in a zip file",
        "users":[5], 
        "catego":[10]
    },
    {
        "title":"javascript intermedio",
        "description":"Descripcion del curso, que no pase de 255 caracteres",
        "image":"https://elcomercio.pe/resizer/jNCpa33Il7p1UN9X60AXaNlsCQ8=/580x330/smart/filters:format(jpeg):quality(75)/cloudfront-us-east-1.images.arcpublishing.com/elcomercio/Z42PI3LJHRH3BLJF7SV65SDGH4.jpg",
        "lenguage":"ENGLISH", 
        "price":100,
        "pro":false, 
        "duration":"La duracion va escrita en string", 
        "content":"En esta seccion se describe el contenido del curso",
        "dificulty":"BASIC",
        "requirement":"Aca en texto plano de lo que requiere el alumno para cursar el curso",
        "learnTo":["Importante","va todo","en texto","y String","lo que aprendera"],
        "studyMethod":"Metodo en como se entregara el curso, importante, es un texto plano, no mas de 255 caracteres",
        "users":[1], 
        "catego":[1]
    },
    {
        "title":"java",
        "description":"Descripcion del curso, que no pase de 255 caracteres",
        "image":"https://hotmart.s3.amazonaws.com/product_pictures/6fe2df11-fe4f-44e6-9b9e-558808b17b9e/Java.png",
        "lenguage":"ENGLISH", 
        "price":29.99,
        "pro":false, 
        "duration":"La duracion va escrita en string", 
        "content":"En esta seccion se describe el contenido del curso",
        "dificulty":"BASIC",
        "requirement":"Aca en texto plano de lo que requiere el alumno para cursar el curso",
        "learnTo":["Importante","va todo","en texto","y String","lo que aprendera"],
        "studyMethod":"Metodo en como se entregara el curso, importante, es un texto plano, no mas de 255 caracteres",
        "users":[2], 
        "catego":[2]
    },
    {
        "title":"Photoshop",
        "description":"Descripcion del curso, que no pase de 255 caracteres",
        "image":"https://burakboga.com/en/wp-content/uploads/sites/2/2022/11/Photoshop-system-requirements.png",
        "lenguage":"ENGLISH", 
        "price":55,
        "pro":false, 
        "duration":"La duracion va escrita en string", 
        "content":"En esta seccion se describe el contenido del curso",
        "dificulty":"BASIC",
        "requirement":"Aca en texto plano de lo que requiere el alumno para cursar el curso",
        "learnTo":["Importante","va todo","en texto","y String","lo que aprendera"],
        "studyMethod":"Metodo en como se entregara el curso, importante, es un texto plano, no mas de 255 caracteres",
        "users":[3], 
        "catego":[3]
    },
    {
        "title":"Python",
        "description":"Descripcion del curso, que no pase de 255 caracteres",
        "image":"https://programacion.net/files/article/20160721020723_python-logo.png",
        "lenguage":"ESPAÑOL", 
        "price":40,
        "pro":false, 
        "duration":"La duracion va escrita en string", 
        "content":"En esta seccion se describe el contenido del curso",
        "dificulty":"MEDIUM",
        "requirement":"Aca en texto plano de lo que requiere el alumno para cursar el curso",
        "learnTo":["Importante","va todo","en texto","y String","lo que aprendera"],
        "studyMethod":"Metodo en como se entregara el curso, importante, es un texto plano, no mas de 255 caracteres",
        "users":[4], 
        "catego":[4]
    },
    {
        "title":"Github",
        "description":"Descripcion del curso, que no pase de 255 caracteres",
        "image":"https://www.malwarebytes.com/blog/news/2023/03/easset_upload_file13810_262604_e.png",
        "lenguage":"ENGLISH", 
        "price":25,
        "pro":true, 
        "duration":"La duracion va escrita en string", 
        "content":"En esta seccion se describe el contenido del curso",
        "dificulty":"ADVANCED",
        "requirement":"Aca en texto plano de lo que requiere el alumno para cursar el curso",
        "learnTo":["Importante","va todo","en texto","y String","lo que aprendera"],
        "studyMethod":"Metodo en como se entregara el curso, importante, es un texto plano, no mas de 255 caracteres",
        "users":[5], 
        "catego":[5]
    },
    {
        "title":"Linux",
        "description":"Descripcion del curso, que no pase de 255 caracteres",
        "image":"https://voidlinux.eu/wp-content/uploads/2019/04/cropped-linux-logo-void-linux-web-eu.png",
        "lenguage":"ESPAÑOL", 
        "price":69.25,
        "pro":false, 
        "duration":"La duracion va escrita en string", 
        "content":"En esta seccion se describe el contenido del curso",
        "dificulty":"BASIC",
        "requirement":"Aca en texto plano de lo que requiere el alumno para cursar el curso",
        "learnTo":["Importante","va todo","en texto","y String","lo que aprendera"],
        "studyMethod":"Metodo en como se entregara el curso, importante, es un texto plano, no mas de 255 caracteres",
        "users":[1], 
        "catego":[6]
    },
    {
        "title":"React",
        "description":"Descripcion del curso, que no pase de 255 caracteres",
        "image":"https://blog.wildix.com/wp-content/uploads/2020/06/react-logo.jpg",
        "lenguage":"ENGLISH", 
        "price":75,
        "pro":true, 
        "duration":"La duracion va escrita en string", 
        "content":"En esta seccion se describe el contenido del curso",
        "dificulty":"MEDIUM",
        "requirement":"Aca en texto plano de lo que requiere el alumno para cursar el curso",
        "learnTo":["Importante","va todo","en texto","y String","lo que aprendera"],
        "studyMethod":"Metodo en como se entregara el curso, importante, es un texto plano, no mas de 255 caracteres",
        "users":[2], 
        "catego":[7]
    },
    {
        "title":"Telecomunicaciones",
        "description":"Descripcion del curso, que no pase de 255 caracteres",
        "image":"https://bdrinformatica.com/wp-content/uploads/2022/07/sistemas-de-telecomunicaciones.jpg",
        "lenguage":"ENGLISH", 
        "price":75,
        "pro":true, 
        "duration":"La duracion va escrita en string", 
        "content":"En esta seccion se describe el contenido del curso",
        "dificulty":"BASIC",
        "requirement":"Aca en texto plano de lo que requiere el alumno para cursar el curso",
        "learnTo":["Importante","va todo","en texto","y String","lo que aprendera"],
        "studyMethod":"Metodo en como se entregara el curso, importante, es un texto plano, no mas de 255 caracteres",
        "users":[3], 
        "catego":[8]
    },
    {
        "title":"Postgre",
        "description":"Descripcion del curso, que no pase de 255 caracteres",
        "image":"https://proyectoa.com/wp-content/uploads/2010/11/postgresql.png",
        "lenguage":"ESPAÑOL", 
        "price":44.99,
        "pro":true, 
        "duration":"La duracion va escrita en string", 
        "content":"En esta seccion se describe el contenido del curso",
        "dificulty":"MEDIUM",
        "requirement":"Aca en texto plano de lo que requiere el alumno para cursar el curso",
        "learnTo":["Importante","va todo","en texto","y String","lo que aprendera"],
        "studyMethod":"Metodo en como se entregara el curso, importante, es un texto plano, no mas de 255 caracteres",
        "users":[4], 
        "catego":[9]
    },
    {
        "title":"Henry",
        "description":"Descripcion del curso, que no pase de 255 caracteres",
        "image":"https://assets.soyhenry.com/logoOG.png",
        "lenguage":"ESPAÑOL", 
        "price":4000,
        "pro":false, 
        "duration":"La duracion va escrita en string", 
        "content":"En esta seccion se describe el contenido del curso",
        "dificulty":"MEDIUM",
        "requirement":"Aca en texto plano de lo que requiere el alumno para cursar el curso",
        "learnTo":["Importante","va todo","en texto","y String","lo que aprendera"],
        "studyMethod":"Metodo en como se entregara el curso, importante, es un texto plano, no mas de 255 caracteres",
        "users":[5], 
        "catego":[10]
    },
]