module.exports = [
    {
        "title":"javascript intermedio",
        "description":"Descripcion del curso, que no pase de 255 caracteres",
        "image":"https://elcomercio.pe/resizer/jNCpa33Il7p1UN9X60AXaNlsCQ8=/580x330/smart/filters:format(jpeg):quality(75)/cloudfront-us-east-1.images.arcpublishing.com/elcomercio/Z42PI3LJHRH3BLJF7SV65SDGH4.jpg",
        "lenguage":"ENGLISH", 
        "price":100,
        "pro":false, 
        "duration":"La duracion va escrita en string", 
        "content":"En esta seccion se describe el contenido del curso",
        "dificulty":"BASIC",
        "requirement":"Aca en texto plano de lo que requiere el alumno para cursar el curso",
        "learnTo":["Importante","va todo","en texto","y String","lo que aprendera"],
        "studyMethod":"Metodo en como se entregara el curso, importante, es un texto plano, no mas de 255 caracteres",
        "users":[1], 
        "catego":[1]
    },
    {
        "title":"java",
        "description":"Descripcion del curso, que no pase de 255 caracteres",
        "image":"https://hotmart.s3.amazonaws.com/product_pictures/6fe2df11-fe4f-44e6-9b9e-558808b17b9e/Java.png",
        "lenguage":"ENGLISH", 
        "price":29.99,
        "pro":false, 
        "duration":"La duracion va escrita en string", 
        "content":"En esta seccion se describe el contenido del curso",
        "dificulty":"BASIC",
        "requirement":"Aca en texto plano de lo que requiere el alumno para cursar el curso",
        "learnTo":["Importante","va todo","en texto","y String","lo que aprendera"],
        "studyMethod":"Metodo en como se entregara el curso, importante, es un texto plano, no mas de 255 caracteres",
        "users":[2], 
        "catego":[2]
    },
    {
        "title":"Photoshop",
        "description":"Descripcion del curso, que no pase de 255 caracteres",
        "image":"https://burakboga.com/en/wp-content/uploads/sites/2/2022/11/Photoshop-system-requirements.png",
        "lenguage":"ENGLISH", 
        "price":55,
        "pro":false, 
        "duration":"La duracion va escrita en string", 
        "content":"En esta seccion se describe el contenido del curso",
        "dificulty":"BASIC",
        "requirement":"Aca en texto plano de lo que requiere el alumno para cursar el curso",
        "learnTo":["Importante","va todo","en texto","y String","lo que aprendera"],
        "studyMethod":"Metodo en como se entregara el curso, importante, es un texto plano, no mas de 255 caracteres",
        "users":[4], 
        "catego":[3]
    },
    {
        "title":"Python",
        "description":"Descripcion del curso, que no pase de 255 caracteres",
        "image":"https://programacion.net/files/article/20160721020723_python-logo.png",
        "lenguage":"ESPAÑOL", 
        "price":40,
        "pro":false, 
        "duration":"La duracion va escrita en string", 
        "content":"En esta seccion se describe el contenido del curso",
        "dificulty":"MEDIUM",
        "requirement":"Aca en texto plano de lo que requiere el alumno para cursar el curso",
        "learnTo":["Importante","va todo","en texto","y String","lo que aprendera"],
        "studyMethod":"Metodo en como se entregara el curso, importante, es un texto plano, no mas de 255 caracteres",
        "users":[1], 
        "catego":[4]
    },
    {
        "title":"Github",
        "description":"Descripcion del curso, que no pase de 255 caracteres",
        "image":"https://www.malwarebytes.com/blog/news/2023/03/easset_upload_file13810_262604_e.png",
        "lenguage":"ENGLISH", 
        "price":25,
        "pro":true, 
        "duration":"La duracion va escrita en string", 
        "content":"En esta seccion se describe el contenido del curso",
        "dificulty":"ADVANCED",
        "requirement":"Aca en texto plano de lo que requiere el alumno para cursar el curso",
        "learnTo":["Importante","va todo","en texto","y String","lo que aprendera"],
        "studyMethod":"Metodo en como se entregara el curso, importante, es un texto plano, no mas de 255 caracteres",
        "users":[2], 
        "catego":[5]
    },
    {
        "title":"Linux",
        "description":"Descripcion del curso, que no pase de 255 caracteres",
        "image":"https://voidlinux.eu/wp-content/uploads/2019/04/cropped-linux-logo-void-linux-web-eu.png",
        "lenguage":"ESPAÑOL", 
        "price":69.25,
        "pro":false, 
        "duration":"La duracion va escrita en string", 
        "content":"En esta seccion se describe el contenido del curso",
        "dificulty":"BASIC",
        "requirement":"Aca en texto plano de lo que requiere el alumno para cursar el curso",
        "learnTo":["Importante","va todo","en texto","y String","lo que aprendera"],
        "studyMethod":"Metodo en como se entregara el curso, importante, es un texto plano, no mas de 255 caracteres",
        "users":[4], 
        "catego":[6]
    },
    {
        "title":"React",
        "description":"Descripcion del curso, que no pase de 255 caracteres",
        "image":"https://blog.wildix.com/wp-content/uploads/2020/06/react-logo.jpg",
        "lenguage":"ENGLISH", 
        "price":75,
        "pro":true, 
        "duration":"La duracion va escrita en string", 
        "content":"En esta seccion se describe el contenido del curso",
        "dificulty":"MEDIUM",
        "requirement":"Aca en texto plano de lo que requiere el alumno para cursar el curso",
        "learnTo":["Importante","va todo","en texto","y String","lo que aprendera"],
        "studyMethod":"Metodo en como se entregara el curso, importante, es un texto plano, no mas de 255 caracteres",
        "users":[1], 
        "catego":[7]
    },
    {
        "title":"Telecomunicaciones",
        "description":"Descripcion del curso, que no pase de 255 caracteres",
        "image":"https://bdrinformatica.com/wp-content/uploads/2022/07/sistemas-de-telecomunicaciones.jpg",
        "lenguage":"ENGLISH", 
        "price":75,
        "pro":true, 
        "duration":"La duracion va escrita en string", 
        "content":"En esta seccion se describe el contenido del curso",
        "dificulty":"BASIC",
        "requirement":"Aca en texto plano de lo que requiere el alumno para cursar el curso",
        "learnTo":["Importante","va todo","en texto","y String","lo que aprendera"],
        "studyMethod":"Metodo en como se entregara el curso, importante, es un texto plano, no mas de 255 caracteres",
        "users":[2], 
        "catego":[8]
    },
    {
        "title":"Postgre",
        "description":"Descripcion del curso, que no pase de 255 caracteres",
        "image":"https://proyectoa.com/wp-content/uploads/2010/11/postgresql.png",
        "lenguage":"ESPAÑOL", 
        "price":44.99,
        "pro":true, 
        "duration":"La duracion va escrita en string", 
        "content":"En esta seccion se describe el contenido del curso",
        "dificulty":"MEDIUM",
        "requirement":"Aca en texto plano de lo que requiere el alumno para cursar el curso",
        "learnTo":["Importante","va todo","en texto","y String","lo que aprendera"],
        "studyMethod":"Metodo en como se entregara el curso, importante, es un texto plano, no mas de 255 caracteres",
        "users":[4], 
        "catego":[9]
    },
    {
        "title":"Henry",
        "description":"Descripcion del curso, que no pase de 255 caracteres",
        "image":"https://assets.soyhenry.com/logoOG.png",
        "lenguage":"ESPAÑOL", 
        "price":4000,
        "pro":false, 
        "duration":"La duracion va escrita en string", 
        "content":"En esta seccion se describe el contenido del curso",
        "dificulty":"MEDIUM",
        "requirement":"Aca en texto plano de lo que requiere el alumno para cursar el curso",
        "learnTo":["Importante","va todo","en texto","y String","lo que aprendera"],
        "studyMethod":"Metodo en como se entregara el curso, importante, es un texto plano, no mas de 255 caracteres",
        "users":[1], 
        "catego":[10]
    },
    {
        "title":"javascript intermedio",
        "description":"Descripcion del curso, que no pase de 255 caracteres",
        "image":"https://elcomercio.pe/resizer/jNCpa33Il7p1UN9X60AXaNlsCQ8=/580x330/smart/filters:format(jpeg):quality(75)/cloudfront-us-east-1.images.arcpublishing.com/elcomercio/Z42PI3LJHRH3BLJF7SV65SDGH4.jpg",
        "lenguage":"ENGLISH", 
        "price":100,
        "pro":false, 
        "duration":"La duracion va escrita en string", 
        "content":"En esta seccion se describe el contenido del curso",
        "dificulty":"BASIC",
        "requirement":"Aca en texto plano de lo que requiere el alumno para cursar el curso",
        "learnTo":["Importante","va todo","en texto","y String","lo que aprendera"],
        "studyMethod":"Metodo en como se entregara el curso, importante, es un texto plano, no mas de 255 caracteres",
        "users":[1], 
        "catego":[1]
    },
    {
        "title":"java",
        "description":"Descripcion del curso, que no pase de 255 caracteres",
        "image":"https://hotmart.s3.amazonaws.com/product_pictures/6fe2df11-fe4f-44e6-9b9e-558808b17b9e/Java.png",
        "lenguage":"ENGLISH", 
        "price":29.99,
        "pro":false, 
        "duration":"La duracion va escrita en string", 
        "content":"En esta seccion se describe el contenido del curso",
        "dificulty":"BASIC",
        "requirement":"Aca en texto plano de lo que requiere el alumno para cursar el curso",
        "learnTo":["Importante","va todo","en texto","y String","lo que aprendera"],
        "studyMethod":"Metodo en como se entregara el curso, importante, es un texto plano, no mas de 255 caracteres",
        "users":[2], 
        "catego":[2]
    },
    {
        "title":"Photoshop",
        "description":"Descripcion del curso, que no pase de 255 caracteres",
        "image":"https://burakboga.com/en/wp-content/uploads/sites/2/2022/11/Photoshop-system-requirements.png",
        "lenguage":"ENGLISH", 
        "price":55,
        "pro":false, 
        "duration":"La duracion va escrita en string", 
        "content":"En esta seccion se describe el contenido del curso",
        "dificulty":"BASIC",
        "requirement":"Aca en texto plano de lo que requiere el alumno para cursar el curso",
        "learnTo":["Importante","va todo","en texto","y String","lo que aprendera"],
        "studyMethod":"Metodo en como se entregara el curso, importante, es un texto plano, no mas de 255 caracteres",
        "users":[4], 
        "catego":[3]
    },
    {
        "title":"Python",
        "description":"Descripcion del curso, que no pase de 255 caracteres",
        "image":"https://programacion.net/files/article/20160721020723_python-logo.png",
        "lenguage":"ESPAÑOL", 
        "price":40,
        "pro":false, 
        "duration":"La duracion va escrita en string", 
        "content":"En esta seccion se describe el contenido del curso",
        "dificulty":"MEDIUM",
        "requirement":"Aca en texto plano de lo que requiere el alumno para cursar el curso",
        "learnTo":["Importante","va todo","en texto","y String","lo que aprendera"],
        "studyMethod":"Metodo en como se entregara el curso, importante, es un texto plano, no mas de 255 caracteres",
        "users":[1], 
        "catego":[4]
    },
    {
        "title":"Github",
        "description":"Descripcion del curso, que no pase de 255 caracteres",
        "image":"https://www.malwarebytes.com/blog/news/2023/03/easset_upload_file13810_262604_e.png",
        "lenguage":"ENGLISH", 
        "price":25,
        "pro":true, 
        "duration":"La duracion va escrita en string", 
        "content":"En esta seccion se describe el contenido del curso",
        "dificulty":"ADVANCED",
        "requirement":"Aca en texto plano de lo que requiere el alumno para cursar el curso",
        "learnTo":["Importante","va todo","en texto","y String","lo que aprendera"],
        "studyMethod":"Metodo en como se entregara el curso, importante, es un texto plano, no mas de 255 caracteres",
        "users":[2], 
        "catego":[5]
    },
    {
        "title":"Linux",
        "description":"Descripcion del curso, que no pase de 255 caracteres",
        "image":"https://voidlinux.eu/wp-content/uploads/2019/04/cropped-linux-logo-void-linux-web-eu.png",
        "lenguage":"ESPAÑOL", 
        "price":69.25,
        "pro":false, 
        "duration":"La duracion va escrita en string", 
        "content":"En esta seccion se describe el contenido del curso",
        "dificulty":"BASIC",
        "requirement":"Aca en texto plano de lo que requiere el alumno para cursar el curso",
        "learnTo":["Importante","va todo","en texto","y String","lo que aprendera"],
        "studyMethod":"Metodo en como se entregara el curso, importante, es un texto plano, no mas de 255 caracteres",
        "users":[4], 
        "catego":[6]
    },
    {
        "title":"React",
        "description":"Descripcion del curso, que no pase de 255 caracteres",
        "image":"https://blog.wildix.com/wp-content/uploads/2020/06/react-logo.jpg",
        "lenguage":"ENGLISH", 
        "price":75,
        "pro":true, 
        "duration":"La duracion va escrita en string", 
        "content":"En esta seccion se describe el contenido del curso",
        "dificulty":"MEDIUM",
        "requirement":"Aca en texto plano de lo que requiere el alumno para cursar el curso",
        "learnTo":["Importante","va todo","en texto","y String","lo que aprendera"],
        "studyMethod":"Metodo en como se entregara el curso, importante, es un texto plano, no mas de 255 caracteres",
        "users":[1], 
        "catego":[7]
    },
    {
        "title":"Telecomunicaciones",
        "description":"Descripcion del curso, que no pase de 255 caracteres",
        "image":"https://bdrinformatica.com/wp-content/uploads/2022/07/sistemas-de-telecomunicaciones.jpg",
        "lenguage":"ENGLISH", 
        "price":75,
        "pro":true, 
        "duration":"La duracion va escrita en string", 
        "content":"En esta seccion se describe el contenido del curso",
        "dificulty":"BASIC",
        "requirement":"Aca en texto plano de lo que requiere el alumno para cursar el curso",
        "learnTo":["Importante","va todo","en texto","y String","lo que aprendera"],
        "studyMethod":"Metodo en como se entregara el curso, importante, es un texto plano, no mas de 255 caracteres",
        "users":[2], 
        "catego":[8]
    },
    {
        "title":"Postgre",
        "description":"Descripcion del curso, que no pase de 255 caracteres",
        "image":"https://proyectoa.com/wp-content/uploads/2010/11/postgresql.png",
        "lenguage":"ESPAÑOL", 
        "price":44.99,
        "pro":true, 
        "duration":"La duracion va escrita en string", 
        "content":"En esta seccion se describe el contenido del curso",
        "dificulty":"MEDIUM",
        "requirement":"Aca en texto plano de lo que requiere el alumno para cursar el curso",
        "learnTo":["Importante","va todo","en texto","y String","lo que aprendera"],
        "studyMethod":"Metodo en como se entregara el curso, importante, es un texto plano, no mas de 255 caracteres",
        "users":[4], 
        "catego":[9]
    },
    {
        "title":"Henry",
        "description":"Descripcion del curso, que no pase de 255 caracteres",
        "image":"https://assets.soyhenry.com/logoOG.png",
        "lenguage":"ESPAÑOL", 
        "price":4000,
        "pro":false, 
        "duration":"La duracion va escrita en string", 
        "content":"En esta seccion se describe el contenido del curso",
        "dificulty":"MEDIUM",
        "requirement":"Aca en texto plano de lo que requiere el alumno para cursar el curso",
        "learnTo":["Importante","va todo","en texto","y String","lo que aprendera"],
        "studyMethod":"Metodo en como se entregara el curso, importante, es un texto plano, no mas de 255 caracteres",
        "users":[1], 
        "catego":[10]
    },
    {
        "title":"javascript intermedio",
        "description":"Descripcion del curso, que no pase de 255 caracteres",
        "image":"https://elcomercio.pe/resizer/jNCpa33Il7p1UN9X60AXaNlsCQ8=/580x330/smart/filters:format(jpeg):quality(75)/cloudfront-us-east-1.images.arcpublishing.com/elcomercio/Z42PI3LJHRH3BLJF7SV65SDGH4.jpg",
        "lenguage":"ENGLISH", 
        "price":100,
        "pro":false, 
        "duration":"La duracion va escrita en string", 
        "content":"En esta seccion se describe el contenido del curso",
        "dificulty":"BASIC",
        "requirement":"Aca en texto plano de lo que requiere el alumno para cursar el curso",
        "learnTo":["Importante","va todo","en texto","y String","lo que aprendera"],
        "studyMethod":"Metodo en como se entregara el curso, importante, es un texto plano, no mas de 255 caracteres",
        "users":[1], 
        "catego":[1]
    },
    {
        "title":"java",
        "description":"Descripcion del curso, que no pase de 255 caracteres",
        "image":"https://hotmart.s3.amazonaws.com/product_pictures/6fe2df11-fe4f-44e6-9b9e-558808b17b9e/Java.png",
        "lenguage":"ENGLISH", 
        "price":29.99,
        "pro":false, 
        "duration":"La duracion va escrita en string", 
        "content":"En esta seccion se describe el contenido del curso",
        "dificulty":"BASIC",
        "requirement":"Aca en texto plano de lo que requiere el alumno para cursar el curso",
        "learnTo":["Importante","va todo","en texto","y String","lo que aprendera"],
        "studyMethod":"Metodo en como se entregara el curso, importante, es un texto plano, no mas de 255 caracteres",
        "users":[2], 
        "catego":[2]
    },
    {
        "title":"Photoshop",
        "description":"Descripcion del curso, que no pase de 255 caracteres",
        "image":"https://burakboga.com/en/wp-content/uploads/sites/2/2022/11/Photoshop-system-requirements.png",
        "lenguage":"ENGLISH", 
        "price":55,
        "pro":false, 
        "duration":"La duracion va escrita en string", 
        "content":"En esta seccion se describe el contenido del curso",
        "dificulty":"BASIC",
        "requirement":"Aca en texto plano de lo que requiere el alumno para cursar el curso",
        "learnTo":["Importante","va todo","en texto","y String","lo que aprendera"],
        "studyMethod":"Metodo en como se entregara el curso, importante, es un texto plano, no mas de 255 caracteres",
        "users":[4], 
        "catego":[3]
    },
    {
        "title":"Python",
        "description":"Descripcion del curso, que no pase de 255 caracteres",
        "image":"https://programacion.net/files/article/20160721020723_python-logo.png",
        "lenguage":"ESPAÑOL", 
        "price":40,
        "pro":false, 
        "duration":"La duracion va escrita en string", 
        "content":"En esta seccion se describe el contenido del curso",
        "dificulty":"MEDIUM",
        "requirement":"Aca en texto plano de lo que requiere el alumno para cursar el curso",
        "learnTo":["Importante","va todo","en texto","y String","lo que aprendera"],
        "studyMethod":"Metodo en como se entregara el curso, importante, es un texto plano, no mas de 255 caracteres",
        "users":[1], 
        "catego":[4]
    },
    {
        "title":"Github",
        "description":"Descripcion del curso, que no pase de 255 caracteres",
        "image":"https://www.malwarebytes.com/blog/news/2023/03/easset_upload_file13810_262604_e.png",
        "lenguage":"ENGLISH", 
        "price":25,
        "pro":true, 
        "duration":"La duracion va escrita en string", 
        "content":"En esta seccion se describe el contenido del curso",
        "dificulty":"ADVANCED",
        "requirement":"Aca en texto plano de lo que requiere el alumno para cursar el curso",
        "learnTo":["Importante","va todo","en texto","y String","lo que aprendera"],
        "studyMethod":"Metodo en como se entregara el curso, importante, es un texto plano, no mas de 255 caracteres",
        "users":[2], 
        "catego":[5]
    },
    {
        "title":"Linux",
        "description":"Descripcion del curso, que no pase de 255 caracteres",
        "image":"https://voidlinux.eu/wp-content/uploads/2019/04/cropped-linux-logo-void-linux-web-eu.png",
        "lenguage":"ESPAÑOL", 
        "price":69.25,
        "pro":false, 
        "duration":"La duracion va escrita en string", 
        "content":"En esta seccion se describe el contenido del curso",
        "dificulty":"BASIC",
        "requirement":"Aca en texto plano de lo que requiere el alumno para cursar el curso",
        "learnTo":["Importante","va todo","en texto","y String","lo que aprendera"],
        "studyMethod":"Metodo en como se entregara el curso, importante, es un texto plano, no mas de 255 caracteres",
        "users":[4], 
        "catego":[6]
    },
    {
        "title":"React",
        "description":"Descripcion del curso, que no pase de 255 caracteres",
        "image":"https://blog.wildix.com/wp-content/uploads/2020/06/react-logo.jpg",
        "lenguage":"ENGLISH", 
        "price":75,
        "pro":true, 
        "duration":"La duracion va escrita en string", 
        "content":"En esta seccion se describe el contenido del curso",
        "dificulty":"MEDIUM",
        "requirement":"Aca en texto plano de lo que requiere el alumno para cursar el curso",
        "learnTo":["Importante","va todo","en texto","y String","lo que aprendera"],
        "studyMethod":"Metodo en como se entregara el curso, importante, es un texto plano, no mas de 255 caracteres",
        "users":[1], 
        "catego":[7]
    },
    {
        "title":"Telecomunicaciones",
        "description":"Descripcion del curso, que no pase de 255 caracteres",
        "image":"https://bdrinformatica.com/wp-content/uploads/2022/07/sistemas-de-telecomunicaciones.jpg",
        "lenguage":"ENGLISH", 
        "price":75,
        "pro":true, 
        "duration":"La duracion va escrita en string", 
        "content":"En esta seccion se describe el contenido del curso",
        "dificulty":"BASIC",
        "requirement":"Aca en texto plano de lo que requiere el alumno para cursar el curso",
        "learnTo":["Importante","va todo","en texto","y String","lo que aprendera"],
        "studyMethod":"Metodo en como se entregara el curso, importante, es un texto plano, no mas de 255 caracteres",
        "users":[2], 
        "catego":[8]
    },
    {
        "title":"Postgre",
        "description":"Descripcion del curso, que no pase de 255 caracteres",
        "image":"https://proyectoa.com/wp-content/uploads/2010/11/postgresql.png",
        "lenguage":"ESPAÑOL", 
        "price":44.99,
        "pro":true, 
        "duration":"La duracion va escrita en string", 
        "content":"En esta seccion se describe el contenido del curso",
        "dificulty":"MEDIUM",
        "requirement":"Aca en texto plano de lo que requiere el alumno para cursar el curso",
        "learnTo":["Importante","va todo","en texto","y String","lo que aprendera"],
        "studyMethod":"Metodo en como se entregara el curso, importante, es un texto plano, no mas de 255 caracteres",
        "users":[4], 
        "catego":[9]
    },
    {
        "title":"Henry",
        "description":"Descripcion del curso, que no pase de 255 caracteres",
        "image":"https://assets.soyhenry.com/logoOG.png",
        "lenguage":"ESPAÑOL", 
        "price":4000,
        "pro":false, 
        "duration":"La duracion va escrita en string", 
        "content":"En esta seccion se describe el contenido del curso",
        "dificulty":"MEDIUM",
        "requirement":"Aca en texto plano de lo que requiere el alumno para cursar el curso",
        "learnTo":["Importante","va todo","en texto","y String","lo que aprendera"],
        "studyMethod":"Metodo en como se entregara el curso, importante, es un texto plano, no mas de 255 caracteres",
        "users":[1], 
        "catego":[10]
    },
        {
        "title":"javascript intermedio",
        "description":"Descripcion del curso, que no pase de 255 caracteres",
        "image":"https://elcomercio.pe/resizer/jNCpa33Il7p1UN9X60AXaNlsCQ8=/580x330/smart/filters:format(jpeg):quality(75)/cloudfront-us-east-1.images.arcpublishing.com/elcomercio/Z42PI3LJHRH3BLJF7SV65SDGH4.jpg",
        "lenguage":"ENGLISH", 
        "price":100,
        "pro":false, 
        "duration":"La duracion va escrita en string", 
        "content":"En esta seccion se describe el contenido del curso",
        "dificulty":"BASIC",
        "requirement":"Aca en texto plano de lo que requiere el alumno para cursar el curso",
        "learnTo":["Importante","va todo","en texto","y String","lo que aprendera"],
        "studyMethod":"Metodo en como se entregara el curso, importante, es un texto plano, no mas de 255 caracteres",
        "users":[1], 
        "catego":[1]
    },
    {
        "title":"java",
        "description":"Descripcion del curso, que no pase de 255 caracteres",
        "image":"https://hotmart.s3.amazonaws.com/product_pictures/6fe2df11-fe4f-44e6-9b9e-558808b17b9e/Java.png",
        "lenguage":"ENGLISH", 
        "price":29.99,
        "pro":false, 
        "duration":"La duracion va escrita en string", 
        "content":"En esta seccion se describe el contenido del curso",
        "dificulty":"BASIC",
        "requirement":"Aca en texto plano de lo que requiere el alumno para cursar el curso",
        "learnTo":["Importante","va todo","en texto","y String","lo que aprendera"],
        "studyMethod":"Metodo en como se entregara el curso, importante, es un texto plano, no mas de 255 caracteres",
        "users":[2], 
        "catego":[2]
    },
    {
        "title":"Photoshop",
        "description":"Descripcion del curso, que no pase de 255 caracteres",
        "image":"https://burakboga.com/en/wp-content/uploads/sites/2/2022/11/Photoshop-system-requirements.png",
        "lenguage":"ENGLISH", 
        "price":55,
        "pro":false, 
        "duration":"La duracion va escrita en string", 
        "content":"En esta seccion se describe el contenido del curso",
        "dificulty":"BASIC",
        "requirement":"Aca en texto plano de lo que requiere el alumno para cursar el curso",
        "learnTo":["Importante","va todo","en texto","y String","lo que aprendera"],
        "studyMethod":"Metodo en como se entregara el curso, importante, es un texto plano, no mas de 255 caracteres",
        "users":[4], 
        "catego":[3]
    },
    {
        "title":"Python",
        "description":"Descripcion del curso, que no pase de 255 caracteres",
        "image":"https://programacion.net/files/article/20160721020723_python-logo.png",
        "lenguage":"ESPAÑOL", 
        "price":40,
        "pro":false, 
        "duration":"La duracion va escrita en string", 
        "content":"En esta seccion se describe el contenido del curso",
        "dificulty":"MEDIUM",
        "requirement":"Aca en texto plano de lo que requiere el alumno para cursar el curso",
        "learnTo":["Importante","va todo","en texto","y String","lo que aprendera"],
        "studyMethod":"Metodo en como se entregara el curso, importante, es un texto plano, no mas de 255 caracteres",
        "users":[1], 
        "catego":[4]
    },
    {
        "title":"Github",
        "description":"Descripcion del curso, que no pase de 255 caracteres",
        "image":"https://www.malwarebytes.com/blog/news/2023/03/easset_upload_file13810_262604_e.png",
        "lenguage":"ENGLISH", 
        "price":25,
        "pro":true, 
        "duration":"La duracion va escrita en string", 
        "content":"En esta seccion se describe el contenido del curso",
        "dificulty":"ADVANCED",
        "requirement":"Aca en texto plano de lo que requiere el alumno para cursar el curso",
        "learnTo":["Importante","va todo","en texto","y String","lo que aprendera"],
        "studyMethod":"Metodo en como se entregara el curso, importante, es un texto plano, no mas de 255 caracteres",
        "users":[2], 
        "catego":[5]
    },
    {
        "title":"Linux",
        "description":"Descripcion del curso, que no pase de 255 caracteres",
        "image":"https://voidlinux.eu/wp-content/uploads/2019/04/cropped-linux-logo-void-linux-web-eu.png",
        "lenguage":"ESPAÑOL", 
        "price":69.25,
        "pro":false, 
        "duration":"La duracion va escrita en string", 
        "content":"En esta seccion se describe el contenido del curso",
        "dificulty":"BASIC",
        "requirement":"Aca en texto plano de lo que requiere el alumno para cursar el curso",
        "learnTo":["Importante","va todo","en texto","y String","lo que aprendera"],
        "studyMethod":"Metodo en como se entregara el curso, importante, es un texto plano, no mas de 255 caracteres",
        "users":[4], 
        "catego":[6]
    },
    {
        "title":"React",
        "description":"Descripcion del curso, que no pase de 255 caracteres",
        "image":"https://blog.wildix.com/wp-content/uploads/2020/06/react-logo.jpg",
        "lenguage":"ENGLISH", 
        "price":75,
        "pro":true, 
        "duration":"La duracion va escrita en string", 
        "content":"En esta seccion se describe el contenido del curso",
        "dificulty":"MEDIUM",
        "requirement":"Aca en texto plano de lo que requiere el alumno para cursar el curso",
        "learnTo":["Importante","va todo","en texto","y String","lo que aprendera"],
        "studyMethod":"Metodo en como se entregara el curso, importante, es un texto plano, no mas de 255 caracteres",
        "users":[1], 
        "catego":[7]
    },
    {
        "title":"Telecomunicaciones",
        "description":"Descripcion del curso, que no pase de 255 caracteres",
        "image":"https://bdrinformatica.com/wp-content/uploads/2022/07/sistemas-de-telecomunicaciones.jpg",
        "lenguage":"ENGLISH", 
        "price":75,
        "pro":true, 
        "duration":"La duracion va escrita en string", 
        "content":"En esta seccion se describe el contenido del curso",
        "dificulty":"BASIC",
        "requirement":"Aca en texto plano de lo que requiere el alumno para cursar el curso",
        "learnTo":["Importante","va todo","en texto","y String","lo que aprendera"],
        "studyMethod":"Metodo en como se entregara el curso, importante, es un texto plano, no mas de 255 caracteres",
        "users":[2], 
        "catego":[8]
    },
    {
        "title":"Postgre",
        "description":"Descripcion del curso, que no pase de 255 caracteres",
        "image":"https://proyectoa.com/wp-content/uploads/2010/11/postgresql.png",
        "lenguage":"ESPAÑOL", 
        "price":44.99,
        "pro":true, 
        "duration":"La duracion va escrita en string", 
        "content":"En esta seccion se describe el contenido del curso",
        "dificulty":"MEDIUM",
        "requirement":"Aca en texto plano de lo que requiere el alumno para cursar el curso",
        "learnTo":["Importante","va todo","en texto","y String","lo que aprendera"],
        "studyMethod":"Metodo en como se entregara el curso, importante, es un texto plano, no mas de 255 caracteres",
        "users":[4], 
        "catego":[9]
    },
    {
        "title":"Henry",
        "description":"Descripcion del curso, que no pase de 255 caracteres",
        "image":"https://assets.soyhenry.com/logoOG.png",
        "lenguage":"ESPAÑOL", 
        "price":4000,
        "pro":false, 
        "duration":"La duracion va escrita en string", 
        "content":"En esta seccion se describe el contenido del curso",
        "dificulty":"MEDIUM",
        "requirement":"Aca en texto plano de lo que requiere el alumno para cursar el curso",
        "learnTo":["Importante","va todo","en texto","y String","lo que aprendera"],
        "studyMethod":"Metodo en como se entregara el curso, importante, es un texto plano, no mas de 255 caracteres",
        "users":[1], 
        "catego":[10]
    },  
]