module.exports = [
    {
        "title":"javascript intermedio",
        "description":"Descripcion del curso, que no pase de 255 caracteres",
        "image":"https://elcomercio.pe/resizer/jNCpa33Il7p1UN9X60AXaNlsCQ8=/580x330/smart/filters:format(jpeg):quality(75)/cloudfront-us-east-1.images.arcpublishing.com/elcomercio/Z42PI3LJHRH3BLJF7SV65SDGH4.jpg",
        "lenguage":"ENGLISH", 
        "price":100,
        "pro":false, 
        "duration":"La duracion va escrita en string", 
        "content":"En esta seccion se describe el contenido del curso",
        "dificulty":"BASIC",
        "requirement":"Aca en texto plano de lo que requiere el alumno para cursar el curso",
        "learnTo":["Importante","va todo","en texto","y String","lo que aprendera"],
        "studyMethod":"Metodo en como se entregara el curso, importante, es un texto plano, no mas de 255 caracteres",
        "users":[1], 
        "catego":[2]
        },
        {
            "title": "Python Programming",
            "description": "Learn Python programming from scratch",
            "image": "https://example.com/python.jpg",
            "language": "ENGLISH",
            "price": 49.99,
            "pro": true,
            "duration": "10 weeks",
            "content": "Introduction to Python, data structures, loops, functions, and more",
            "difficulty": "MEDIUM",
            "requirement": "Basic understanding of programming concepts",
            "learnTo": ["Build applications with Python", "Work with databases", "Develop web APIs"],
            "studyMethod": "Online video lectures and coding exercises",
            "users": [1],
            "category": [5]
        },
        {
            "title": "Digital Marketing Fundamentals",
            "description": "Master the essentials of digital marketing",
            "image": "https://example.com/digital-marketing.jpg",
            "language": "ENGLISH",
            "price": 79.99,
            "pro": false,
            "duration": "6 weeks",
            "content": "Search engine optimization, social media marketing, email marketing, and analytics",
            "difficulty": "ADVANCED",
            "requirement": "No prior knowledge required",
            "learnTo": ["Create effective marketing strategies", "Optimize website traffic", "Measure campaign performance"],
            "studyMethod": "Interactive online modules and practical assignments",
            "users": [2],
            "category": [3]
        },
        {
            "title": "Introduction to Photography",
            "description": "Discover the art of photography",
            "image": "https://example.com/photography.jpg",
            "language": "ENGLISH",
            "price": 39.99,
            "pro": false,
            "duration": "4 weeks",
            "content": "Camera basics, composition techniques, lighting principles, and editing",
            "difficulty": "ADVANCED",
            "requirement": "No prior experience required",
            "learnTo": ["Capture stunning images", "Master manual camera settings", "Enhance photos using editing software"],
            "studyMethod": "Video tutorials and practical assignments",
            "users": [2],
            "category": [6]
        },
        {
            "title": "Introduction to Machine Learning",
            "description": "Explore the fundamentals of machine learning",
            "image": "https://example.com/machine-learning.jpg",
            "language": "ENGLISH",
            "price": 69.99,
            "pro": true,
            "duration": "8 weeks",
            "content": "Supervised and unsupervised learning, regression, classification, and model evaluation",
            "difficulty": "MEDIUM",
            "requirement": "Basic knowledge of programming and statistics",
            "learnTo": ["Build predictive models", "Apply machine learning algorithms", "Evaluate model performance"],
            "studyMethod": "Online lectures, coding exercises, and case studies",
            "users": [1],
            "category": [5]
        },
        {
            "title": "Graphic Design Essentials",
            "description": "Learn the essential principles of graphic design",
            "image": "https://example.com/graphic-design.jpg",
            "language": "ENGLISH",
            "price": 59.99,
            "pro": false,
            "duration": "6 weeks",
            "content": "Color theory, typography, layout design, and visual communication",
            "difficulty": "MEDIUM",
            "requirement": "No prior experience required",
            "learnTo": ["Create visually appealing designs", "Use design software effectively", "Understand design principles"],
            "studyMethod": "Video tutorials, practical assignments, and design projects",
            "users": [4],
            "category": [6]
        },
        {
            "title": "Financial Planning 101",
            "description": "Master the basics of personal financial planning",
            "image": "https://example.com/financial-planning.jpg",
            "language": "ENGLISH",
            "price": 49.99,
            "pro": false,
            "duration": "4 weeks",
            "content": "Budgeting, saving, investing, and retirement planning",
            "difficulty": "ADVANCED",
            "requirement": "No prior knowledge required",
            "learnTo": ["Manage personal finances effectively", "Create a budget and savings plan", "Make informed investment decisions"],
            "studyMethod": "Online modules, interactive quizzes, and financial exercises",
            "users": [2],
            "category": [4]
        },
        {
            "title": "iOS App Development",
            "description": "Build iOS apps using Swift programming language",
            "image": "https://example.com/ios-development.jpg",
            "language": "ENGLISH",
            "price": 89.99,
            "pro": true,
            "duration": "10 weeks",
            "content": "App architecture, user interface design, data persistence, and app deployment",
            "difficulty": "ADVANCED",
            "requirement": "Knowledge of basic programming concepts",
            "learnTo": ["Develop functional iOS apps", "Implement interactive features", "Publish apps to the App Store"],
            "studyMethod": "Video tutorials, coding exercises, and app development projects",
            "users": [2],
            "category": [5]
        },
        {
            "title": "Creative Writing Workshop",
            "description": "Unleash your creativity through writing",
            "image": "https://example.com/creative-writing.jpg",
            "language": "ENGLISH",
            "price": 49.99,
            "pro": false,
            "duration": "6 weeks",
            "content": "Writing exercises, storytelling techniques, character development, and editing",
            "difficulty": "BASIC",
            "requirement": "No prior experience required",
            "learnTo": ["Develop your writing style", "Craft compelling narratives", "Revise and polish your work"],
            "studyMethod": "Interactive online lessons and writing assignments",
            "users": [2],
            "category": [2]
        },
        {
            "title": "Introduction to Astrophysics",
            "description": "Discover the wonders of the universe",
            "image": "https://example.com/astrophysics.jpg",
            "language": "ENGLISH",
            "price": 59.99,
            "pro": true,
            "duration": "8 weeks",
            "content": "Stellar evolution, cosmology, black holes, and the Big Bang theory",
            "difficulty": "BASIC",
            "requirement": "Basic understanding of physics and mathematics",
            "learnTo": ["Understand the principles of astrophysics", "Explore the mysteries of space", "Grasp the scale of the universe"],
            "studyMethod": "Video lectures, simulations, and observational projects",
            "users": [1],
            "category": [6]
        },
        {
            "title": "Photography Post-Processing",
            "description": "Master the art of editing and retouching photos",
            "image": "https://example.com/photography-editing.jpg",
            "language": "ENGLISH",
            "price": 39.99,
            "pro": false,
            "duration": "4 weeks",
            "content": "Image editing software, color correction, retouching techniques, and creative effects",
            "difficulty": "BASIC",
            "requirement": "Basic photography knowledge",
            "learnTo": ["Enhance photos using editing software", "Apply advanced retouching techniques", "Create stunning visual effects"],
            "studyMethod": "Step-by-step tutorials and hands-on editing assignments",
            "users": [4],
            "category": [6]
        },
        {
            "title": "Introduction to Music Theory",
            "description": "Unlock the secrets of music",
            "image": "https://example.com/music-theory.jpg",
            "language": "ENGLISH",
            "price": 29.99,
            "pro": false,
            "duration": "4 weeks",
            "content": "Notes, scales, chords, rhythm, and basic composition",
            "difficulty": "BASIC",
            "requirement": "No prior knowledge required",
            "learnTo": ["Read sheet music", "Understand musical concepts", "Compose your own melodies"],
            "studyMethod": "Interactive lessons, ear training exercises, and musical examples",
            "users": [1],
            "category": [1]
        },
        {
            "title": "Introduction to Meditation",
            "description": "Discover the power of meditation and mindfulness",
            "image": "https://example.com/meditation.jpg",
            "language": "ENGLISH",
            "price": 19.99,
            "pro": false,
            "duration": "4 weeks",
            "content": "Breathing techniques, relaxation exercises, and cultivating present-moment awareness",
            "difficulty": "BASIC",
            "requirement": "No prior experience required",
            "learnTo": ["Reduce stress and anxiety", "Improve focus and concentration", "Promote overall well-being"],
            "studyMethod": "Guided meditation sessions and mindfulness practices",
            "users": [4],
            "category": [6]
        },
        {
            "title": "Introduction to Graphic Design",
            "description": "Learn the basics of graphic design principles and tools",
            "image": "https://example.com/graphic-design-intro.jpg",
            "language": "ENGLISH",
            "price": 29.99,
            "pro": false,
            "duration": "6 weeks",
            "content": "Color theory, typography, layout design, and using design software",
            "difficulty": "BASIC",
            "requirement": "No prior experience required",
            "learnTo": ["Create visually appealing designs", "Use design software effectively", "Apply design principles to various projects"],
            "studyMethod": "Video tutorials and practical design exercises",
            "users": [4],
            "category": [6]
        },
        {
            "title": "Introduction to Yoga",
            "description": "Embark on a journey of self-discovery through yoga",
            "image": "https://example.com/yoga.jpg",
            "language": "ENGLISH",
            "price": 39.99,
            "pro": false,
            "duration": "8 weeks",
            "content": "Yoga poses, breathing techniques, meditation, and philosophy",
            "difficulty": "BASIC",
            "requirement": "No prior experience required",
            "learnTo": ["Improve physical strength and flexibility", "Cultivate inner peace and mindfulness", "Connect mind, body, and spirit"],
            "studyMethod": "Online video classes and guided yoga sessions",
            "users": [1],
            "category": [5]
        },
        {
            "title": "Introduction to Cryptocurrency",
            "description": "Gain a fundamental understanding of cryptocurrency and blockchain technology",
            "image": "https://example.com/cryptocurrency.jpg",
            "language": "ESPAÑOL",
            "price": 49.99,
            "pro": false,
            "duration": "4 weeks",
            "content": "Cryptocurrency basics, blockchain technology, wallets, and security",
            "difficulty": "BASIC",
            "requirement": "No prior knowledge required",
            "learnTo": ["Understand how cryptocurrencies work", "Invest and trade cryptocurrencies", "Protect your digital assets"],
            "studyMethod": "Online lectures, case studies, and practical exercises",
            "users": [2],
            "category": [2]
        },
        {
            "title": "Introduction to Web Development",
            "description": "Learn the basics of web development and build your own websites",
            "image": "https://example.com/web-development.jpg",
            "language": "ESPAÑOL",
            "price": 49.99,
            "pro": false,
            "duration": "6 weeks",
            "content": "HTML, CSS, JavaScript, responsive design, and web development best practices",
            "difficulty": "BASIC",
            "requirement": "No prior experience required",
            "learnTo": ["Create static and interactive websites", "Style web pages with CSS", "Add functionality with JavaScript"],
            "studyMethod": "Hands-on coding exercises and web development projects",
            "users": [1],
            "category": [3]
        },
        {
            "title": "Digital Marketing Fundamentals",
            "description": "Gain a solid foundation in digital marketing strategies and techniques",
            "image": "https://example.com/digital-marketing.jpg",
            "language": "ESPAÑOL",
            "price": 39.99,
            "pro": false,
            "duration": "4 weeks",
            "content": "SEO, social media marketing, email marketing, and analytics",
            "difficulty": "BASIC",
            "requirement": "No prior knowledge required",
            "learnTo": ["Create effective digital marketing campaigns", "Optimize websites for search engines", "Measure and analyze campaign performance"],
            "studyMethod": "Online lectures, case studies, and practical assignments",
            "users": [1],
            "category": [6]
        },
        {
            "title": "Public Speaking Mastery",
            "description": "Develop effective public speaking and presentation skills",
            "image": "https://example.com/public-speaking.jpg",
            "language": "ESPAÑOL",
            "price": 59.99,
            "pro": true,
            "duration": "8 weeks",
            "content": "Speech preparation, delivery techniques, body language, and overcoming stage fright",
            "difficulty": "MEDIUM",
            "requirement": "No prior experience required",
            "learnTo": ["Deliver confident and persuasive speeches", "Engage and captivate an audience", "Handle Q&A sessions effectively"],
            "studyMethod": "Video tutorials, speech practice, and constructive feedback",
            "users": [1],
            "category": [4]
        },
        {
            "title": "Introduction to Python Programming",
            "description": "Learn the fundamentals of Python programming language",
            "image": "https://example.com/python-programming.jpg",
            "language": "ENGLISH",
            "price": 29.99,
            "pro": false,
            "duration": "6 weeks",
            "content": "Syntax, data types, control flow, functions, and file handling",
            "difficulty": "BASIC",
            "requirement": "No prior programming experience required",
            "learnTo": ["Write Python programs", "Manipulate data structures", "Automate repetitive tasks"],
            "studyMethod": "Interactive coding exercises and programming projects",
            "users": [2],
            "category": [3]
        },
        {
            "title": "Mobile App Development with React Native",
            "description": "Build cross-platform mobile apps using React Native framework",
            "image": "https://example.com/react-native.jpg",
            "language": "ESPAÑOL",
            "price": 69.99,
            "pro": true,
            "duration": "8 weeks",
            "content": "React Native components, navigation, data handling, and integrating with APIs",
            "difficulty": "MEDIUM",
            "requirement": "Basic knowledge of JavaScript and React",
            "learnTo": ["Develop mobile apps for iOS and Android", "Utilize device features", "Publish apps to app stores"],
            "studyMethod": "Hands-on coding projects and app development exercises",
            "users": [4],
            "category": [9]
        },
        {
            "title": "Introduction to Financial Planning",
            "description": "Learn the principles of financial planning and money management",
            "image": "https://example.com/financial-planning.jpg",
            "language": "ENGLISH",
            "price": 49.99,
            "pro": false,
            "duration": "6 weeks",
            "content": "Budgeting, savings strategies, investment basics, and retirement planning",
            "difficulty": "BASIC",
            "requirement": "No prior knowledge required",
            "learnTo": ["Set financial goals", "Create a personal budget", "Make informed investment decisions"],
            "studyMethod": "Online lectures, case studies, and financial planning exercises",
            "users": [4],
            "category": [5]
        },
        {
            "title": "Introduction to Photoshop",
            "description": "Master the essential tools and techniques of Adobe Photoshop",
            "image": "https://example.com/photoshop.jpg",
            "language": "ESPAÑOL",
            "price": 39.99,
            "pro": false,
            "duration": "4 weeks",
            "content": "Image manipulation, retouching, filters, and photo editing workflows",
            "difficulty": "MEDIUM",
            "requirement": "No prior experience required",
            "learnTo": ["Edit and enhance photos", "Create digital artwork", "Work with layers and masks"],
            "studyMethod": "Step-by-step tutorials and hands-on Photoshop projects",
            "users": [1],
            "category": [6]
        },
        {
            "title": "Introduction to Cybersecurity",
            "description": "Gain foundational knowledge in cybersecurity and protect against online threats",
            "image": "https://example.com/cybersecurity.jpg",
            "language": "ESPAÑOL",
            "price": 59.99,
            "pro": false,
            "duration": "8 weeks",
            "content": "Network security, encryption, threat detection, and incident response",
            "difficulty": "MEDIUM",
            "requirement": "Basic computer literacy",
            "learnTo": ["Identify and mitigate common cybersecurity risks", "Implement security measures", "Respond to security incidents"],
            "studyMethod": "Interactive lessons, practical exercises, and simulated cybersecurity scenarios",
            "users": [4],
            "category": [3]
        },
        {
            "title": "Introduction to Music Production",
            "description": "Explore the world of music production and learn to create your own tracks",
            "image": "https://example.com/music-production.jpg",
            "language": "ENGLISH",
            "price": 79.99,
            "pro": true,
            "duration": "10 weeks",
            "content": "Recording, editing, mixing, and mastering music using digital audio workstations",
            "difficulty": "MEDIUM",
            "requirement": "No prior experience required",
            "learnTo": ["Compose melodies and harmonies", "Use virtual instruments and effects", "Produce professional-quality tracks"],
            "studyMethod": "Hands-on projects, music production exercises, and feedback",
            "users": [2],
            "category": [3]
        },
        {
            "title": "Introduction to Data Science",
            "description": "Learn the fundamentals of data science and explore data-driven insights",
            "image": "https://example.com/data-science.jpg",
            "language": "ESPAÑOL",
            "price": 69.99,
            "pro": false,
            "duration": "8 weeks",
            "content": "Data manipulation, visualization, statistical analysis, and machine learning basics",
            "difficulty": "MEDIUM",
            "requirement": "Basic knowledge of programming and statistics",
            "learnTo": ["Analyze and visualize data", "Apply statistical techniques", "Build predictive models"],
            "studyMethod": "Interactive data analysis projects and case studies",
            "users": [4],
            "category": [1]
        },
        {
            "title": "Introduction to Creative Writing",
            "description": "Unleash your creativity and develop your writing skills",
            "image": "https://example.com/creative-writing.jpg",
            "language": "ESPAÑOL",
            "price": 39.99,
            "pro": false,
            "duration": "6 weeks",
            "content": "Narrative techniques, character development, storytelling, and poetry",
            "difficulty": "BASIC",
            "requirement": "No prior experience required",
            "learnTo": ["Craft compelling stories", "Create vivid characters", "Experiment with different writing styles"],
            "studyMethod": "Writing exercises, prompts, and feedback from instructors",
            "users": [1],
            "category": [4]
        },
        {
            "title": "Introduction to E-commerce",
            "description": "Discover the world of online business and learn to build an e-commerce store",
            "image": "https://example.com/e-commerce.jpg",
            "language": "ESPAÑOL",
            "price": 49.99,
            "pro": false,
            "duration": "6 weeks",
            "content": "Product selection, store setup, payment gateways, and marketing strategies",
            "difficulty": "BASIC",
            "requirement": "No prior knowledge required",
            "learnTo": ["Create and manage an online store", "Optimize product listings", "Drive traffic and increase sales"],
            "studyMethod": "Guided tutorials, case studies, and practical e-commerce projects",
            "users": [4],
            "category": [5]
        },
        {
            "title": "Introduction to Graphic Design",
            "description": "Learn the principles of graphic design and create visually appealing designs",
            "image": "https://example.com/graphic-design.jpg",
            "language": "ENGLISH",
            "price": 59.99,
            "pro": true,
            "duration": "8 weeks",
            "content": "Typography, color theory, layout design, and digital design tools",
            "difficulty": "MEDIUM",
            "requirement": "No prior experience required",
            "learnTo": ["Create logos, posters, and marketing materials", "Apply design principles", "Use graphic design software effectively"],
            "studyMethod": "Hands-on design projects, critiques, and design exercises",
            "users": [2],
            "category": [4]
        },
        {
            "title": "Introduction to Cryptocurrency",
            "description": "Explore the world of cryptocurrencies and blockchain technology",
            "image": "https://example.com/cryptocurrency.jpg",
            "language": "ENGLISH",
            "price": 69.99,
            "pro": false,
            "duration": "8 weeks",
            "content": "Bitcoin, Ethereum, smart contracts, and decentralized finance",
            "difficulty": "BASIC",
            "requirement": "Basic knowledge of technology and finance",
            "learnTo": ["Understand blockchain technology", "Invest in cryptocurrencies", "Navigate cryptocurrency exchanges"],
            "studyMethod": "Online lectures, case studies, and practical exercises",
            "users": [2],
            "category": [2]
        },
        {
            "title": "Introduction to Fashion Design",
            "description": "Learn the basics of fashion design and unleash your creativity",
            "image": "https://example.com/fashion-design.jpg",
            "language": "ENGLISH",
            "price": 49.99,
            "pro": false,
            "duration": "6 weeks",
            "content": "Sketching, garment construction, fabric selection, and fashion trends",
            "difficulty": "BASIC",
            "requirement": "No prior experience required",
            "learnTo": ["Create fashion sketches", "Sew and construct garments", "Develop a fashion collection"],
            "studyMethod": "Hands-on fashion design projects and guidance from industry professionals",
            "users": [1],
            "category": [5]
        },
        {
            "title": "Introduction to Digital Illustration",
            "description": "Master the art of digital illustration using popular design software",
            "image": "https://example.com/digital-illustration.jpg",
            "language": "ESPAÑOL",
            "price": 59.99,
            "pro": true,
            "duration": "8 weeks",
            "content": "Digital drawing techniques, shading, color theory, and composition",
            "difficulty": "MEDIUM",
            "requirement": "Basic knowledge of drawing concepts",
            "learnTo": ["Create digital illustrations", "Use layers and brushes", "Apply textures and special effects"],
            "studyMethod": "Step-by-step tutorials, practice exercises, and digital illustration projects",
            "users": [4],
            "category": [6]
        }
]