const factura ={
    "id":"6AM18290GN7720348",
    "status":"COMPLETED",
    "payment_source":{
        "paypal":{
            "email_address":
            "sb-tbg2d25768523@personal.example.com",
            "account_id":"JEKW4GA74APK6",
            "name":{
                "given_name":"John",
                "surname":"Doe"
            },
            "address":{
                "country_code":"VE"
            }
        }
    },
    "purchase_units":[
        {
            "reference_id":"default",
            "shipping":{
                "name":{
                    "full_name":"John Doe"
                },
                "address":{
                    "address_line_1":"Free Trade Zone",
                    "admin_area_2":"Caracas",
                    "admin_area_1":"Caracas",
                    "postal_code":"1012",
                    "country_code":"VE"
                }
            },
            "payments":{
                "captures":[
                    {
                        "id":"4YT64807TG4215016",
                        "status":"COMPLETED",
                        "amount":{
                            "currency_code":"USD",
                            "value":"45.00"
                        },
                        "final_capture":true,
                        "seller_protection":{
                            "status":"ELIGIBLE",
                            "dispute_categories":[
                                "ITEM_NOT_RECEIVED",
                                "UNAUTHORIZED_TRANSACTION"
                            ]
                        },
                        "seller_receivable_breakdown":{
                            "gross_amount":{
                                "currency_code":"USD",
                                "value":"45.00"
                            },
                            "paypal_fee":{
                                "currency_code":"USD",
                                "value":"2.73"
                            },
                            "net_amount":{
                                "currency_code":"USD",
                                "value":"42.27"
                            }
                        },
                        "links":[
                            {
                                "href":"https://api.sandbox.paypal.com/v2/payments/captures/4YT64807TG4215016",
                                "rel":"self",
                                "method":"GET"
                            },
                            {
                                "href":"https://api.sandbox.paypal.com/v2/payments/captures/4YT64807TG4215016/refund",
                                "rel":"refund",
                                "method":"POST"
                            },
                            {
                                "href":"https://api.sandbox.paypal.com/v2/checkout/orders/6AM18290GN7720348",
                                "rel":"up",
                                "method":"GET"
                            }
                        ],
                        "create_time":"2023-05-22T20:00:17Z",
                        "update_time":"2023-05-22T20:00:17Z"
                    }
                ]
            }
        }
    ],
    "payer":{
        "name":{
            "given_name":"John",
            "surname":"Doe"
        },
        "email_address":"sb-tbg2d25768523@personal.example.com",
        "payer_id":"JEKW4GA74APK6",
        "address":{
            "country_code":"VE"
        }
    },
    "links":[
        {
            "href":"https://api.sandbox.paypal.com/v2/checkout/orders/6AM18290GN7720348",
            "rel":"self",
            "method":"GET"
        }
    ]
}