module.exports = [
  {
    name: "David",
    lastname: "gonzalez",
    email: "David@gmail.com",
    password: "david123",
    description: "Desarrollador full stack, con amplia destresa en Node.js.",
    Is: "INSTRUCTOR",
    numberSales:0,
    assessment: 0,
    studies: "Estudiante actual del famoso bootcamp Henry, en donde amplié mi conocimiento en tales tecnologías; React.js, Express.js, PostgreSQL, Sequelize, entre otras tecnologías. ",
    asset: true,
  },
  {
    name: "Gisell",
    lastname: "Vanegas",
    email: "gisell@gmail.com",
    password: "gisell123",
    description: "Desarrollador full stack, con amplia destresa en Node.js.",
    Is: "INSTRUCTOR",
    numberSales:0,
    assessment: 0,
    studies: "Estudiante actual del famoso bootcamp Henry, en donde amplié mi conocimiento en tales tecnologías; React.js, Express.js, PostgreSQL, Sequelize, entre otras tecnologías. ",
    asset: true,
  },
  {
    name: "Mauricio",
    lastname: "Tejada",
    email: "mauri@gmail.com",
    password: "mauri123",
    description: "Desarrollador full stack, con amplia destresa en Node.js.",
    Is: "INSTRUCTOR",
    numberSales:0,
    assessment: 0,
    studies: "Estudiante actual del famoso bootcamp Henry, en donde amplié mi conocimiento en tales tecnologías; React.js, Express.js, PostgreSQL, Sequelize, entre otras tecnologías. ",
    asset: true,
  },
  {
    name: "Maiger",
    lastname: "Ovalle",
    email: "maiger@gmail.com",
    password: "maiger123",
    description: "Desarrollador full stack, con amplia destresa en Node.js.",
    Is: "INSTRUCTOR",
    numberSales:0,
    assessment: 0,
    studies: "Estudiante actual del famoso bootcamp Henry, en donde amplié mi conocimiento en tales tecnologías; React.js, Express.js, PostgreSQL, Sequelize, entre otras tecnologías. ",
    asset: true,
  },
  {
    name: "Yeison",
    lastname: "Gonzalez",
    email: "yeison@gmail.com",
    password: "yeison123",
    description: "Desarrollador full stack, con amplia destresa en Node.js.",
    Is: "INSTRUCTOR",
    numberSales:0,
    assessment: 0,
    studies: "Estudiante actual del famoso bootcamp Henry, en donde amplié mi conocimiento en tales tecnologías; React.js, Express.js, PostgreSQL, Sequelize, entre otras tecnologías. ",
    asset: true,
  },
];
