module.exports = [
  {
    name: "Alex",
    lastname: "gonzalez",
    email: "alex@gmail.com",
    password: "Alex1234",
    description: "descripcion del user/vendedor",
    Is: "INSTRUCTOR",
    assessment: 4.5,
    studies: "Programacion",
    asset: true,
  },
  {
    name: "Gisell",
    lastname: "Vanegas",
    email: "gisell@gmail.com",
    password: "LamejorContraseña12",
    description: "descripcion del user/vendedor",
    Is: "INSTRUCTOR",
    assessment: 3,
    studies: "Full stack en Henry",
    asset: true,
  },
  {
    name: "User1",
    lastname: "Ingenia",
    email: "user1@gmail.com",
    password: "LamejorContraseña12",
    Is: "STUDENT",
    asset: true,
  },
  {
    name: "Maiger",
    lastname: "Ovalle",
    email: "maiger@gmail.com",
    password: "Contraseña4321",
    description: "descripcion del user/vendedor",
    Is: "INSTRUCTOR",
    assessment: 4.5,
    studies: "Databese con SQL y posgret",
    asset: true,
  },
  {
    name: "User2",
    lastname: "Ingenia",
    email: "user2@gmail.com",
    password: "LamejorContraseña12",
    Is: "STUDENT",
    asset: true,
  },
];
