const cursos = [
  {
    IdCuros: 1,
    title: "Java orientado a objetos",
    descriction:
      "En este curso de Java orientado a objetos, aprenderás a diseñar y desarrollar aplicaciones escalables y mantenibles utilizando conceptos clave como encapsulamiento, herencia y polimorfismo. Aprovecha la oportunidad de dominar uno de los lenguajes de programación más populares del mundo y llevar tus habilidades de programación al siguiente nivel.",
    deliveryMethod: ["Archivo Zip", "Platafoma externa", "online"],
    imgCurso:
      "https://formaciononline.eu/wp-content/uploads/2013/05/curso-java.jpg",
    idiom: "Español",
    price: 29.99,
    duration: "3 meses",
    skills: ["java", "java orientado a objetos", "visual"], //!Lo que aprenderas.
    difficulty: "Basico", //Recordando que cuando se este del lado del registro de curso, este OLE: Basico,Intermedio,Avanzado
    requirements: [
      "conocimiento basico de programación",
      "conocer las variables var, let y const",
    ],
    instructor: "Yeison Gonzalez", // aca para el back llega distinto
    category: ["programacion", "mundo TI", "Tecnoliga"],
    ratings: 4.6,
    sold: [], //!Esta propiedad dira cuantas veces se ah vendido este curso. no se si ya tengan otra forma de llevar la cuenta, lo hago de ejemplo (o pueden ir las facturas)
    idComment: [],
    asset: true,
  },
  {
    IdCuros: 2,
    title: "Desarrollo web con React",
    descriction:
      "Este curso te enseñará a crear aplicaciones web modernas utilizando la popular biblioteca de JavaScript, React. Aprenderás a utilizar componentes, estados y propiedades para crear interfaces de usuario interactivas y dinámicas. Además, también aprenderás a trabajar con herramientas como Webpack y Babel para crear proyectos escalables y eficientes.",
    deliveryMethod: ["Archivo Zip", "Platafoma externa", "online"],
    imgCurso: "https://miro.medium.com/max/1200/1*V8j4TdpJAJWNOYvqv8wUjw.png",
    idiom: "Español",
    price: 49.99,
    duration: "2 meses",
    skills: ["React", "JavaScript", "Desarrollo web"], //!Lo que aprenderas.
    difficulty: "Intermedio",
    requirements: [
      "conocimiento previo de HTML, CSS y JavaScript",
      "haber trabajado con algún framework de JavaScript como Angular o Vue",
    ],
    instructor: "Ana Torres",
    category: ["programacion", "mundo TI", "Tecnoliga"],
    ratings: 4.8,
    sold: [],
    idComment: [],
    asset: true,
  },
  {
    IdCuros: 3,
    title: "Python para ciencia de datos",
    descriction:
      "En este curso de Python para ciencia de datos, aprenderás a utilizar el lenguaje de programación más popular en el mundo de la ciencia de datos. Aprenderás a utilizar bibliotecas como NumPy, Pandas y Matplotlib para análisis de datos, visualización y manipulación. También aprenderás a utilizar herramientas como Jupyter Notebook para crear presentaciones interactivas y compartir tus resultados con otros científicos de datos.",
    deliveryMethod: ["Archivo Zip", "Platafoma externa", "online"],
    imgCurso: "https://miro.medium.com/max/1400/1*tzvqjz7C6xWw2E7f8DIxJQ.png",
    idiom: "Español",
    price: 69.99,
    duration: "4 meses",
    skills: ["Python", "Ciencia de datos", "Análisis de datos"], //!Lo que aprenderas.
    difficulty: "Intermedio",
    requirements: [
      "conocimiento previo de Python",
      "conocimiento básico de estadística y álgebra lineal",
    ],
    instructor: "Pedro Gomez",
    category: ["programacion", "mundo TI", "Ciencia de datos"],
    ratings: 4.7,
    sold: [],
    idComment: [],
    asset: true,
  },
  {
    IdCurso: 4,
    title: "Introducción a la Inteligencia Artificial",
    descriction:
      "En este curso de Introducción a la Inteligencia Artificial, aprenderás los conceptos clave para el diseño y desarrollo de sistemas inteligentes que puedan realizar tareas que requieren inteligencia humana, como el aprendizaje automático y el procesamiento del lenguaje natural. Este curso es ideal para quienes desean adquirir habilidades en una de las áreas de tecnología más prometedoras del mundo.",
    deliveryMethod: ["Archivo PDF", "Plataforma externa", "Online"],
    imgCurso:
      "https://cdn.pixabay.com/photo/2018/03/06/22/56/artificial-intelligence-3200173_960_720.jpg",
    idiom: "Inglés",
    price: 49.99,
    duration: "6 semanas",
    skills: [
      "inteligencia artificial",
      "aprendizaje automático",
      "procesamiento del lenguaje natural",
    ],
    difficulty: "Intermedio",
    requirements: [
      "conocimientos básicos de programación",
      "conocimientos básicos de matemáticas",
    ],
    instructor: "John Smith",
    category: ["tecnología", "informática", "ciencia"],
    ratings: 4.9,
    sold: [],
    idComment: [],
    asset: false,
  },
  {
    IdCurso: 5,
    title: "Diseño gráfico para principiantes",
    descriction:
      "En este curso de Diseño gráfico para principiantes, aprenderás los fundamentos del diseño gráfico y las herramientas clave utilizadas por los profesionales del diseño. Aprenderás a crear diseños atractivos y efectivos para impresión y para la web, y a aplicar principios de diseño para mejorar la estética de tus proyectos. Este curso es ideal para aquellos que desean aprender diseño gráfico desde cero.",
    deliveryMethod: ["Archivo ZIP", "Plataforma externa", "Online"],
    imgCurso:
      "https://cdn.pixabay.com/photo/2017/08/10/02/24/ux-2618570_960_720.png",
    idiom: "Español",
    price: 19.99,
    duration: "4 semanas",
    skills: [
      "diseño gráfico",
      "herramientas de diseño",
      "principios de diseño",
    ],
    difficulty: "Básico",
    requirements: [
      "ningún conocimiento previo requerido",
      "acceso a un software de diseño gráfico (p. ej., Adobe Photoshop o Illustrator)",
    ],
    instructor: "María García",
    category: ["diseño", "creatividad", "arte"],
    ratings: 4.3,
    sold: [],
    idComment: [],
    asset: true,
  },
  {
    IdCurso: 6,
    title: "Desarrollo web con React",
    descriction:
      "En este curso de Desarrollo web con React, aprenderás a construir aplicaciones web modernas y escalables utilizando React, una de las bibliotecas de JavaScript más populares del mundo. Aprenderás a crear componentes reutilizables, gestionar el estado de la aplicación y utilizar herramientas como Webpack y Babel para optimizar el rendimiento. Este curso es ideal para aquellos que desean adquirir habilidades en una de las áreas más demandadas en el desarrollo de software.",
    deliveryMethod: ["Plataforma externa", "Online"],
    imgCurso:
      "https://cdn.pixabay.com/photo/2021/04/06/08/12/programming-6151677_960_720.jpg",
    idiom: "Inglés",
    price: 39.99,
    duration: "8 semanas",
    skills: ["React", "desarrollo web", "JavaScript"],
    difficulty: "Intermedio",
    requirements: [
      "conocimientos básicos de HTML, CSS y JavaScript",
      "acceso a un editor de código (p. ej., Visual Studio Code)",
    ],
    instructor: "Mike Johnson",
    category: ["programación", "tecnología", "informática"],
    ratings: 4.7,
    sold: [],
    idComment: [],
    asset: true,
  },
  {
    IdCurso: 7,
    title: "Marketing digital para emprendedores",
    descriction:
      "En este curso de Marketing digital para emprendedores, aprenderás las estrategias clave para promocionar tu negocio en línea y llegar a un público más amplio. Aprenderás a utilizar herramientas como Google AdWords, Facebook Ads y SEO para mejorar tu visibilidad en línea y atraer clientes potenciales. Este curso es ideal para aquellos que desean adquirir habilidades en marketing digital y hacer crecer su negocio en línea.",
    deliveryMethod: ["Archivo PDF", "Plataforma externa", "Online"],
    imgCurso:
      "https://cdn.pixabay.com/photo/2018/02/12/21/05/digital-marketing-3140913_960_720.jpg",
    idiom: "Español",
    price: 24.99,
    duration: "6 semanas",
    skills: ["marketing digital", "Google AdWords", "Facebook Ads", "SEO"],
    difficulty: "Básico",
    requirements: [
      "ningún conocimiento previo requerido",
      "acceso a una computadora y una conexión a Internet",
    ],
    instructor: "Ana Martínez",
    category: ["negocios", "marketing", "emprendimiento"],
    ratings: 4.5,
    sold: [],
    idComment: [],
    asset: false,
  },
  {
    IdCurso: 8,
    title: "Aprende a tocar guitarra eléctrica",
    descriction:
      "En este curso de guitarra eléctrica, aprenderás a tocar desde cero y dominarás las técnicas avanzadas. Desde los acordes básicos hasta las escalas y solos complejos, este curso tiene todo lo que necesitas para convertirte en un guitarrista experto. Aprenderás de profesionales y tendrás acceso a cientos de lecciones en video y tablaturas para practicar. ¡Toma tu guitarra y empieza a rockear!",
    deliveryMethod: ["Archivo Zip", "Plataforma externa", "Online"],
    imgCurso:
      "https://cdn.pixabay.com/photo/2017/12/09/08/18/guitarist-3001893_960_720.jpg",
    idiom: "Inglés",
    price: 49.99,
    duration: "12 semanas",
    skills: ["guitarra eléctrica", "música", "rock"],
    difficulty: "Intermedio",
    requirements: [
      "tener una guitarra eléctrica",
      "acceso a un amplificador de guitarra (opcional)",
    ],
    instructor: "David Lee",
    category: ["música", "arte", "entretenimiento"],
    ratings: 4.8,
    sold: [],
    idComment: [],
    asset: true,
  },
  {
    IdCurso: 9,
    title: "Diseño de moda para principiantes",
    descriction:
      "En este curso de Diseño de moda, aprenderás las técnicas y habilidades necesarias para diseñar y confeccionar tu propia ropa. Desde los conceptos básicos de diseño hasta la costura y la creación de patrones, este curso te dará todas las herramientas que necesitas para empezar. Aprenderás de profesionales y tendrás acceso a tutoriales en video y patrones descargables para practicar. ¡Crea tu propia moda y desata tu creatividad!",
    deliveryMethod: ["Archivo PDF", "Plataforma externa", "Online"],
    imgCurso:
      "https://cdn.pixabay.com/photo/2018/08/19/15/00/fashion-3615761_960_720.jpg",
    idiom: "Español",
    price: 29.99,
    duration: "10 semanas",
    skills: ["diseño de moda", "costura", "creación de patrones"],
    difficulty: "Básico",
    requirements: [
      "ningún conocimiento previo requerido",
      "acceso a una máquina de coser (opcional)",
    ],
    instructor: "María García",
    category: ["arte", "moda", "creatividad"],
    ratings: 4.6,
    sold: [],
    idComment: [],
    asset: false,
  },
  {
    IdCurso: 10,
    title: "Aprende a hacer sushi como un chef",
    descriction:
      "En este curso de sushi, aprenderás a hacer sushi como un verdadero chef. Aprenderás a preparar arroz de sushi perfectamente cocido, cortar pescado fresco y crear hermosos rollos y nigiri. Este curso te enseñará las técnicas y habilidades necesarias para hacer sushi delicioso en casa. Aprenderás de profesionales y tendrás acceso a cientos de lecciones en video y recetas descargables para practicar. ¡Sé el anfitrión de la fiesta de sushi perfecta!",
    deliveryMethod: ["Archivo PDF", "Plataforma externa", "Online"],
    imgCurso:
      "https://cdn.pixabay.com/photo/2015/11/07/10/00/sushi-1030074_960_720.jpg",
    idiom: "Inglés",
    price: 59.99,
    duration: "6 semanas",
    skills: ["sushi", "cocina", "gastronomía"],
    difficulty: "Avanzado",
    requirements: [
      "tener experiencia previa en la cocina",
      "acceso a ingredientes de sushi frescos",
    ],
    instructor: "Takeshi Nakamura",
    category: ["gastronomía", "cocina", "creatividad"],
    ratings: 4.9,
    sold: [],
    idComment: [],
    asset: true,
  },
  {
    IdCurso: 11,
    title: "Fotografía de paisaje para principiantes",
    descriction:
      "En este curso de fotografía, aprenderás las técnicas y habilidades necesarias para capturar paisajes impresionantes. Desde la composición y la exposición hasta el uso de filtros y la edición, este curso te dará todas las herramientas que necesitas para empezar a tomar fotos impresionantes. Aprenderás de profesionales y tendrás acceso a tutoriales en video y ejercicios prácticos para mejorar tu habilidad. ¡Captura la belleza de la naturaleza con tus propias fotos!",
    deliveryMethod: ["Archivo PDF", "Plataforma externa", "Online"],
    imgCurso:
      "https://cdn.pixabay.com/photo/2016/01/19/16/59/landscape-1149079_960_720.jpg",
    idiom: "Español",
    price: 39.99,
    duration: "8 semanas",
    skills: ["fotografía", "paisaje", "creatividad"],
    difficulty: "Básico",
    requirements: [
      "tener una cámara digital",
      "acceso a una computadora para la edición de fotos",
    ],
    instructor: "Juan Carlos García",
    category: ["arte", "fotografía", "creatividad"],
    ratings: 4.7,
    sold: [],
    idComment: [],
    asset: false,
  },
  {
    IdCurso: 12,
    title: "Fotografía para principiantes",
    descriction:
      "En este curso de fotografía, aprenderás los fundamentos de la fotografía y cómo usar tu cámara para capturar imágenes impresionantes. Aprenderás a configurar la exposición, la apertura y la velocidad de obturación para crear imágenes bien expuestas y con profundidad de campo. Este curso también te enseñará cómo componer tus fotos para crear imágenes visualmente impactantes. Aprenderás de profesionales y tendrás acceso a cientos de lecciones en video y recursos descargables para practicar. ¡Conviértete en un fotógrafo experto!",
    deliveryMethod: ["Archivo PDF", "Plataforma externa", "Online"],
    imgCurso:
      "https://cdn.pixabay.com/photo/2017/08/07/20/34/fashion-2606968_960_720.jpg",
    idiom: "Español",
    price: 49.99,
    duration: "8 semanas",
    skills: ["fotografía", "composición", "exposición"],
    difficulty: "Principiante",
    requirements: [
      "tener una cámara",
      "acceso a una computadora para descargar recursos",
    ],
    instructor: "Annie Leibovitz",
    category: ["arte", "creatividad", "fotografía"],
    ratings: 4.7,
    sold: [],
    idComment: [],
    asset: true,
  },
  {
    IdCurso: 13,
    title: "Aprende a cocinar comida italiana",
    descriction:
      "En este curso de cocina, aprenderás a cocinar deliciosos platos italianos desde cero. Aprenderás a preparar platos clásicos como la pizza, la pasta y las salsas italianas. Este curso también te enseñará cómo seleccionar los ingredientes adecuados, cómo usar las herramientas de cocina y cómo presentar tus platos de manera atractiva. Aprenderás de chefs profesionales y tendrás acceso a cientos de lecciones en video y recursos descargables para practicar. ¡Conviértete en un chef italiano experto!",
    deliveryMethod: ["Archivo PDF", "Plataforma externa", "Online"],
    imgCurso:
      "https://cdn.pixabay.com/photo/2017/05/07/08/56/pizza-2296473_960_720.jpg",
    idiom: "Inglés",
    price: 69.99,
    duration: "10 semanas",
    skills: [
      "cocina italiana",
      "preparación de alimentos",
      "presentación de platos",
    ],
    difficulty: "Intermedio",
    requirements: [
      "acceso a una cocina con utensilios básicos",
      "disponibilidad de los ingredientes necesarios",
    ],
    instructor: "Giada De Laurentiis",
    category: ["gastronomía", "creatividad", "entretenimiento"],
    ratings: 4.8,
    sold: [],
    idComment: [],
    asset: true,
  },
  {
    IdCurso: 14,
    title: "Introducción a la Inteligencia Artificial",
    descriction:
      "En este curso de Introducción a la Inteligencia Artificial, aprenderás los conceptos fundamentales de la IA y su aplicación en el mundo real. Aprenderás a programar algoritmos de IA para resolver problemas complejos y también comprenderás cómo las redes neuronales y los sistemas de aprendizaje automático funcionan en la toma de decisiones automatizadas. Este curso también te proporcionará una base sólida para abordar temas avanzados en el campo de la IA. ¡Conviértete en un experto en IA y transforma el futuro!",
    deliveryMethod: ["Archivo PDF", "Plataforma externa", "Online"],
    imgCurso:
      "https://cdn.pixabay.com/photo/2020/02/03/22/10/artificial-intelligence-4812817_960_720.jpg",
    idiom: "Inglés",
    price: 99.99,
    duration: "12 semanas",
    skills: ["inteligencia artificial", "algoritmos", "redes neuronales"],
    difficulty: "Avanzado",
    requirements: [
      "conocimiento básico de programación",
      "acceso a una computadora con capacidad para ejecutar algoritmos",
    ],
    instructor: "Andrew Ng",
    category: ["tecnología", "innovación", "ciencias"],
    ratings: 4.9,
    sold: [],
    idComment: [],
    asset: true,
  },
  {
    IdCurso: 15,
    title: "Marketing Digital para Emprendedores",
    descriction:
      "En este curso de Marketing Digital para Emprendedores, aprenderás las mejores prácticas y estrategias para promocionar tu negocio en línea. Aprenderás a usar las redes sociales, el correo electrónico y el SEO para atraer nuevos clientes y construir tu marca. También aprenderás a realizar campañas publicitarias efectivas y a medir el éxito de tus esfuerzos de marketing. Este curso te dará las herramientas necesarias para llevar tu negocio al siguiente nivel en el mundo digital. ¡Conviértete en un experto en Marketing Digital y haz crecer tu negocio!",
    deliveryMethod: ["Archivo PDF", "Plataforma externa", "Online"],
    imgCurso:
      "https://cdn.pixabay.com/photo/2018/03/07/17/25/social-media-3207717_960_720.jpg",
    idiom: "Español",
    price: 49.99,
    duration: "8 semanas",
    skills: ["marketing digital", "redes sociales", "publicidad en línea"],
    difficulty: "Intermedio",
    requirements: [
      "tener una computadora con acceso a Internet",
      "tener una cuenta de correo electrónico",
    ],
    instructor: "Neil Patel",
    category: ["negocios", "emprendimiento", "marketing"],
    ratings: 4.7,
    sold: [],
    idComment: [],
    asset: true,
  },
  {
    IdCurso: 16,
    title: "Diseño de Jardines",
    descriction:
      "En este curso de Diseño de Jardines, aprenderás a crear jardines hermosos y funcionales para hogares y negocios. Aprenderás a utilizar diferentes técnicas de diseño, a elegir las plantas adecuadas y a crear un plan de mantenimiento para mantener tu jardín en buen estado. Este curso también te proporcionará una base sólida para abordar temas avanzados en el campo del diseño de paisajes. ¡Conviértete en un experto en Diseño de Jardines y transforma los espacios verdes!",
    deliveryMethod: ["Archivo PDF", "Plataforma externa", "Online"],
    imgCurso:
      "https://cdn.pixabay.com/photo/2018/06/25/17/24/garden-3491917_960_720.jpg",
    idiom: "Español",
    price: 49.99,
    duration: "10 semanas",
    skills: ["diseño de jardines", "paisajismo", "horticultura"],
    difficulty: "Intermedio",
    requirements: [
      "tener una computadora con acceso a Internet",
      "tener interés en el diseño de jardines y el paisajismo",
    ],
    instructor: "María Rodríguez",
    category: ["decoración", "paisajismo", "jardinería"],
    ratings: 4.8,
    sold: [],
    idComment: [],
    asset: true,
  },
  {
    IdCurso: 17,
    title: "Fotografía de Paisajes",
    descriction:
      "En este curso de Fotografía de Paisajes, aprenderás las técnicas y habilidades necesarias para capturar hermosas imágenes de paisajes. Aprenderás a utilizar diferentes tipos de cámaras y lentes, a ajustar la exposición y a aprovechar la luz natural para crear fotos impresionantes. También aprenderás técnicas avanzadas como el enfoque selectivo y la composición. Este curso te dará las herramientas necesarias para llevar tus habilidades de fotografía al siguiente nivel. ¡Conviértete en un experto en Fotografía de Paisajes y captura la belleza del mundo!",
    deliveryMethod: ["Archivo PDF", "Plataforma externa", "Online"],
    imgCurso:
      "https://cdn.pixabay.com/photo/2017/08/06/15/05/landscape-2596235_960_720.jpg",
    idiom: "Inglés",
    price: 69.99,
    duration: "12 semanas",
    skills: [
      "fotografía de paisajes",
      "composición",
      "ajuste de la exposición",
    ],
    difficulty: "Intermedio",
    requirements: [
      "tener una cámara DSLR o de lentes intercambiables",
      "tener conocimientos básicos de fotografía",
    ],
    instructor: "Ansel Adams",
    category: ["fotografía", "arte", "naturaleza"],
    ratings: 4.9,
    sold: [],
    idComment: [],
    asset: true,
  },
  {
    IdCurso: 18,
    title: "Aprende a tocar guitarra",
    descriction:
      "En este curso de guitarra para principiantes, aprenderás los conceptos básicos para tocar la guitarra acústica o eléctrica. Aprenderás acordes, ritmos, técnicas de digitación y canciones populares. Además, te enseñaremos cómo afinar la guitarra y cómo cuidarla para que siempre suene bien. Conviértete en un guitarrista con este curso completo y conviértete en el alma de cualquier reunión.",
    deliveryMethod: ["Archivo PDF", "Plataforma externa", "Online"],
    imgCurso:
      "https://cdn.pixabay.com/photo/2017/12/23/17/41/guitar-3032127_960_720.jpg",
    idiom: "Español",
    price: 39.99,
    duration: "8 semanas",
    skills: ["guitarra", "música", "tocar instrumentos"],
    difficulty: "Básico",
    requirements: [
      "tener una guitarra acústica o eléctrica",
      "tener interés en aprender a tocar la guitarra",
    ],
    instructor: "David Gómez",
    category: ["música", "instrumentos", "arte"],
    ratings: 4.7,
    sold: [],
    idComment: [],
    asset: true,
  },
  {
    IdCurso: 19,
    title: "Aprende a cocinar comida japonesa",
    descriction:
      "En este curso de cocina japonesa, aprenderás a preparar los platos más populares de la gastronomía japonesa. Aprenderás a hacer sushi, sashimi, tempura y muchos otros platos deliciosos. Además, te enseñaremos sobre los ingredientes japoneses y la cultura gastronómica del país. Este curso es perfecto para cualquier persona interesada en la comida japonesa y en aprender a cocinarla.",
    deliveryMethod: ["Archivo PDF", "Plataforma externa", "Online"],
    imgCurso:
      "https://cdn.pixabay.com/photo/2017/07/16/18/02/sushi-2512745_960_720.jpg",
    idiom: "Inglés",
    price: 59.99,
    duration: "12 semanas",
    skills: ["cocina japonesa", "sushi", "gastronomía"],
    difficulty: "Intermedio",
    requirements: [
      "tener una cocina y utensilios básicos",
      "tener interés en aprender a cocinar comida japonesa",
    ],
    instructor: "Yumi Nakamura",
    category: ["gastronomía", "cocina", "cultura"],
    ratings: 4.9,
    sold: [],
    idComment: [],
    asset: true,
  },
  {
    IdCurso: 20,
    title: "Introducción a la meditación",
    descriction:
      "En este curso de introducción a la meditación, aprenderás a meditar de manera efectiva y a incorporar la práctica de la meditación en tu vida diaria. Aprenderás diferentes técnicas de meditación y cómo utilizarlas para reducir el estrés, mejorar tu concentración y aumentar tu bienestar emocional. Conviértete en un meditador más consciente y aprende a manejar mejor tus emociones con este curso práctico y completo.",
    deliveryMethod: ["Archivo PDF", "Plataforma externa", "Online"],
    imgCurso:
      "https://cdn.pixabay.com/photo/2017/03/17/04/07/meditation-2156830_960_720.jpg",
    idiom: "Español",
    price: 19.99,
    duration: "4 semanas",
    skills: ["meditación", "mindfulness", "bienestar emocional"],
    difficulty: "Básico",
    requirements: [
      "tener interés en aprender a meditar",
      "disponer de un espacio tranquilo para la meditación",
    ],
    instructor: "Laura Rodríguez",
    category: ["salud mental", "bienestar", "espiritualidad"],
    ratings: 4.8,
    sold: [],
    idComment: [],
    asset: true,
  },
  {
    IdCurso: 21,
    title: "Fotografía de paisajes",
    descriction:
      "En este curso de fotografía de paisajes, aprenderás a tomar fotografías impresionantes de paisajes naturales y urbanos. Aprenderás técnicas de composición, iluminación y exposición para crear imágenes impactantes y visualmente atractivas. Además, te enseñaremos cómo utilizar herramientas de edición para mejorar tus fotos y darles un toque profesional. Conviértete en un fotógrafo de paisajes experto con este curso completo y práctico.",
    deliveryMethod: ["Archivo PDF", "Plataforma externa", "Online"],
    imgCurso:
      "https://cdn.pixabay.com/photo/2017/09/25/13/12/landscape-2788472_960_720.jpg",
    idiom: "Inglés",
    price: 49.99,
    duration: "10 semanas",
    skills: ["fotografía", "paisajes", "arte"],
    difficulty: "Intermedio",
    requirements: [
      "tener una cámara DSLR o mirrorless",
      "tener interés en aprender técnicas avanzadas de fotografía",
    ],
    instructor: "John Smith",
    category: ["fotografía", "arte", "creatividad"],
    ratings: 4.5,
    sold: [],
    idComment: [],
    asset: true,
  },
  {
    IdCurso: 22,
    title: "Introducción a la programación en Python",
    descriction:
      "En este curso de introducción a la programación en Python, aprenderás los conceptos fundamentales de la programación y cómo aplicarlos en el lenguaje de programación Python. Aprenderás a utilizar variables, estructuras de control de flujo, funciones y módulos en Python para crear programas simples. Además, te enseñaremos cómo utilizar herramientas de depuración para solucionar errores en tu código. Conviértete en un programador en Python con este curso práctico y completo.",
    deliveryMethod: ["Archivo PDF", "Plataforma externa", "Online"],
    imgCurso:
      "https://cdn.pixabay.com/photo/2020/06/12/06/24/python-5289611_960_720.jpg",
    idiom: "Español",
    price: 24.99,
    duration: "8 semanas",
    skills: ["programación", "Python", "informática"],
    difficulty: "Básico",
    requirements: [
      "tener interés en aprender a programar",
      "disponer de un ordenador con acceso a internet",
    ],
    instructor: "Juan Pérez",
    category: ["programación", "mundo TI", "tecnología"],
    ratings: 4.6,
    sold: [],
    idComment: [],
    asset: true,
  },
  {
    IdCurso: 23,
    title: "Diseño de páginas web con HTML y CSS",
    descriction:
      "En este curso de diseño de páginas web con HTML y CSS, aprenderás a crear páginas web modernas y visualmente atractivas utilizando lenguajes de marcado y estilos en cascada. Aprenderás a utilizar etiquetas HTML para estructurar el contenido de tu sitio web y a utilizar CSS para darle estilo y personalidad. Además, te enseñaremos cómo utilizar herramientas de diseño web para crear prototipos y maquetas de tu sitio. Conviértete en un diseñador web profesional con este curso completo y práctico.",
    deliveryMethod: ["Archivo PDF", "Plataforma externa", "Online"],
    imgCurso:
      "https://cdn.pixabay.com/photo/2015/04/20/13/17/work-731198_960_720.jpg",
    idiom: "Inglés",
    price: 39.99,
    duration: "12 semanas",
    skills: ["diseño web", "HTML", "CSS"],
    difficulty: "Intermedio",
    requirements: [
      "tener conocimientos básicos de HTML y CSS",
      "disponer de un editor de código y un navegador web",
    ],
    instructor: "Emily Davis",
    category: ["diseño web", "creatividad", "tecnología"],
    ratings: 4.8,
    sold: [],
    idComment: [],
    asset: true,
  },
  {
    IdCurso: 24,
    title: "Aprende a tocar la guitarra eléctrica",
    descriction:
      "En este curso de guitarra eléctrica, aprenderás desde cero a tocar este instrumento y a desarrollar tu propio estilo. Aprenderás a afinar la guitarra, a leer tablaturas, a tocar acordes y escalas básicas, así como a tocar canciones completas de diferentes géneros musicales. Además, te enseñaremos cómo utilizar efectos de sonido para darle más personalidad a tu música. Conviértete en un guitarrista eléctrico con este curso práctico y completo.",
    deliveryMethod: ["Plataforma externa", "Online"],
    imgCurso:
      "https://cdn.pixabay.com/photo/2017/05/21/11/39/guitar-2335570_960_720.jpg",
    idiom: "Español",
    price: 49.99,
    duration: "16 semanas",
    skills: ["música", "guitarra eléctrica", "creatividad"],
    difficulty: "Intermedio",
    requirements: [
      "tener una guitarra eléctrica y un amplificador",
      "tener conocimientos básicos de teoría musical",
    ],
    instructor: "David Gómez",
    category: ["música", "arte", "entretenimiento"],
    ratings: 4.9,
    sold: [],
    idComment: [],
    asset: true,
  },
  {
    IdCurso: 25,
    title: "Curso de cocina internacional",
    descriction:
      "En este curso de cocina internacional, aprenderás a preparar platos de diferentes partes del mundo y a experimentar con sabores y texturas únicas. Aprenderás a utilizar diferentes ingredientes y técnicas de cocción para crear platos exóticos y deliciosos. Además, te enseñaremos cómo presentar tus platos de manera atractiva y elegante. Conviértete en un chef internacional con este curso completo y práctico.",
    deliveryMethod: ["Plataforma externa", "Online"],
    imgCurso:
      "https://cdn.pixabay.com/photo/2017/08/12/14/07/food-2634782_960_720.jpg",
    idiom: "Español",
    price: 69.99,
    duration: "20 semanas",
    skills: ["cocina", "gastronomía", "creatividad"],
    difficulty: "Intermedio",
    requirements: [
      "tener una cocina equipada con utensilios y electrodomésticos básicos",
      "tener conocimientos básicos de cocina",
    ],
    instructor: "Ana Martínez",
    category: ["gastronomía", "arte culinario", "entretenimiento"],
    ratings: 4.7,
    sold: [],
    idComment: [],
    asset: true,
  },
  {
    IdCurso: 26,
    title: "Fotografía creativa con tu smartphone",
    descriction:
      "En este curso de fotografía creativa con tu smartphone, aprenderás a sacar el máximo provecho de la cámara de tu teléfono para capturar imágenes impactantes y originales. Aprenderás a utilizar diferentes técnicas de composición, iluminación y edición para crear fotos que destaquen en redes sociales y en cualquier otro medio. Además, te enseñaremos cómo utilizar aplicaciones y accesorios para mejorar tus resultados. Conviértete en un fotógrafo creativo con este curso práctico y completo.",
    deliveryMethod: ["Plataforma externa", "Online"],
    imgCurso:
      "https://cdn.pixabay.com/photo/2016/01/19/16/48/camera-1149313_960_720.jpg",
    idiom: "Español",
    price: 39.99,
    duration: "8 semanas",
    skills: ["fotografía", "smartphone", "creatividad"],
    difficulty: "Intermedio",
    requirements: [
      "tener un smartphone con cámara",
      "tener conocimientos básicos de fotografía",
    ],
    instructor: "Laura Pérez",
    category: ["fotografía", "arte", "tecnología"],
    ratings: 4.8,
    sold: [],
    idComment: [],
    asset: true,
  },
  {
    IdCurso: 27,
    title: "Diseño de interiores para espacios pequeños",
    descriction:
      "En este curso de diseño de interiores para espacios pequeños, aprenderás a crear ambientes funcionales y estéticos en lugares reducidos. Aprenderás a utilizar diferentes técnicas de distribución, iluminación y decoración para sacar el máximo partido de cada metro cuadrado. Además, te enseñaremos cómo elegir los materiales, colores y objetos adecuados para lograr el efecto deseado. Conviértete en un diseñador de interiores experto en espacios pequeños con este curso práctico y completo.",
    deliveryMethod: ["Plataforma externa", "Online"],
    imgCurso:
      "https://cdn.pixabay.com/photo/2017/03/23/14/02/kitchen-2165756_960_720.jpg",
    idiom: "Español",
    price: 59.99,
    duration: "12 semanas",
    skills: ["diseño de interiores", "decoración", "espacios pequeños"],
    difficulty: "Intermedio",
    requirements: [
      "tener interés por el diseño de interiores",
      "tener acceso a un espacio reducido para diseñar",
    ],
    instructor: "Carlos Rodríguez",
    category: ["diseño", "arte", "hogar"],
    ratings: 4.6,
    sold: [],
    idComment: [],
    asset: true,
  },
  {
    IdCurso: 28,
    title: "Marketing digital para negocios locales",
    descriction:
      "En este curso de marketing digital para negocios locales, aprenderás a utilizar las herramientas digitales más efectivas para promocionar tu negocio en internet. Aprenderás a crear campañas publicitarias en redes sociales, email marketing y SEO local para atraer nuevos clientes y fidelizar a los existentes. Además, te enseñaremos cómo medir los resultados y ajustar tus estrategias para maximizar tus beneficios. Conviértete en un experto en marketing digital para negocios locales con este curso práctico y completo.",
    deliveryMethod: ["Plataforma externa", "Online"],
    imgCurso:
      "https://cdn.pixabay.com/photo/2017/09/25/09/58/marketing-2785782_960_720.jpg",
    idiom: "Español",
    price: 49.99,
    duration: "10 semanas",
    skills: ["marketing digital", "negocios locales", "publicidad"],
    difficulty: "Intermedio",
    requirements: [
      "tener un negocio local",
      "tener conocimientos básicos de internet",
    ],
    instructor: "María Fernández",
    category: ["negocios", "marketing", "tecnología"],
    ratings: 4.9,
    sold: [],
    idComment: [],
    asset: true,
  },
  {
    IdCurso: 29,
    title: "Inglés para viajeros",
    descriction:
      "En este curso de inglés para viajeros, aprenderás a comunicarte en inglés en situaciones cotidianas que se presentan en un viaje. Aprenderás vocabulario y expresiones útiles para pedir información, hacer reservas, comprar en tiendas y restaurantes, entre otras cosas. Además, te enseñaremos cómo pronunciar correctamente y mejorar tu comprensión auditiva. Conviértete en un viajero seguro y preparado con este curso práctico y completo.",
    deliveryMethod: ["Archivo PDF", "Audio"],
    imgCurso:
      "https://cdn.pixabay.com/photo/2017/06/26/20/07/english-2444274_960_720.jpg",
    idiom: "Español",
    price: 19.99,
    duration: "4 semanas",
    skills: ["inglés", "viajes", "comunicación"],
    difficulty: "Básico",
    requirements: [
      "tener un nivel básico de inglés",
      "tener interés en mejorar la comunicación en inglés en viajes",
    ],
    instructor: "John Smith",
    category: ["idiomas", "viajes", "educación"],
    ratings: 4.5,
    sold: [],
    idComment: [],
    asset: true,
  },
  {
    IdCurso: 30,
    title: "Introducción a la inteligencia artificial",
    descriction:
      "En este curso de introducción a la inteligencia artificial, aprenderás los fundamentos de la IA y cómo se aplican en la vida cotidiana. Aprenderás los conceptos clave como aprendizaje automático, redes neuronales y procesamiento del lenguaje natural. Además, te enseñaremos cómo construir y entrenar tus propios modelos de IA utilizando herramientas de programación como Python y TensorFlow. Conviértete en un experto en IA con este curso práctico y completo.",
    deliveryMethod: ["Plataforma externa", "Online"],
    imgCurso:
      "https://cdn.pixabay.com/photo/2018/10/08/11/12/artificial-intelligence-3739883_960_720.jpg",
    idiom: "Español",
    price: 99.99,
    duration: "12 semanas",
    skills: ["inteligencia artificial", "aprendizaje automático", "Python"],
    difficulty: "Avanzado",
    requirements: [
      "tener conocimientos de programación en Python",
      "conocer los fundamentos de estadística",
    ],
    instructor: "Juan Pérez",
    category: ["tecnología", "programación", "educación"],
    ratings: 4.8,
    sold: [],
    idComment: [],
    asset: true,
  },
];

module.exports = cursos;
