const cursos = [
  {
    IdCuros: 1,
    title: "Java orientado a objetos",
    descriction: "Texto descriptivo",
    imgCurso:
      "https://formaciononline.eu/wp-content/uploads/2013/05/curso-java.jpg",
    idiom: "Español",
    price: 29.99,
    duration: "3 meses",
    skills: ["java", "java orientado a objetos", "visual"],
    difficulty: "Basico", //Recordando que cuando se este del lado del registro de curso, este OLE: Basico,Intermedio,Avanzado
    instructor: "Yeison Gonzalez", // aca para el back llega distinto
    category: ["programacion", "mundo TI", "Tecnoliga"],
    ratings: 4.6,
    asset: true,
  },
  {
    IdCuros: 2,
    title: "Photoshop",
    descriction: "Texto descriptivo",
    imgCurso:
      "https://imactions.agency/wp-content/uploads/2022/12/que-es-photoshop.jpg",
    idiom: "Español",
    price: 25,
    duration: "una semana",
    skills: ["photoshop", "diseño grafico", "paleta de colores"],
    difficulty: "Medio",
    instructor: "Felipe Garcia",
    category: ["Diseño grafico", "Marketing"],
    ratings: 3.3,
    asset: true,
  },
  {
    IdCurso: 3,
    title: "Introducción a Python",
    description: "Curso introductorio a Python para programadores novatos",
    imgCurso:
      "https://cdn.pixabay.com/photo/2015/04/23/17/41/python-736887_1280.png",
    idiom: "Español",
    price: 19.99,
    duration: "2 meses",
    skills: ["python", "programación", "novatos"],
    difficulty: "Basico",
    instructor: "Maria Garcia",
    category: ["programación", "mundo TI", "Tecnología"],
    ratings: 4.8,
    asset: true,
  },
  {
    IdCurso: 4,
    title: "Machine Learning con TensorFlow",
    description: "Curso de Machine Learning para expertos en TensorFlow",
    imgCurso:
      "https://cdn.pixabay.com/photo/2018/05/08/08/38/artificial-intelligence-3382507_1280.png",
    idiom: "Inglés",
    price: 99.99,
    duration: "6 meses",
    skills: ["machine learning", "TensorFlow", "programación"],
    difficulty: "Avanzado",
    instructor: "John Smith",
    category: ["inteligencia artificial", "ciencia de datos", "Tecnología"],
    ratings: 4.9,
    asset: true,
  },
  {
    IdCurso: 5,
    title: "Desarrollo web con React",
    description: "Curso de desarrollo web utilizando la librería React",
    imgCurso:
      "https://cdn.pixabay.com/photo/2017/08/05/11/16/logo-2582748_1280.png",
    idiom: "Español",
    price: 49.99,
    duration: "4 meses",
    skills: ["React", "desarrollo web", "programación"],
    difficulty: "Intermedio",
    instructor: "Carlos Rodriguez",
    category: ["desarrollo web", "mundo TI", "Tecnología"],
    ratings: 4.7,
    asset: true,
  },
  {
    IdCurso: 6,
    title: "Introducción a la inteligencia artificial",
    description:
      "Curso introductorio para aprender los fundamentos de la inteligencia artificial",
    imgCurso:
      "https://cdn.pixabay.com/photo/2017/08/05/11/16/logo-2582748_1280.png",
    idiom: "Español",
    price: 29.99,
    duration: "2 meses",
    skills: [
      "Inteligencia artificial",
      "aprendizaje automático",
      "programación",
    ],
    difficulty: "Básico",
    instructor: "María García",
    category: ["Inteligencia artificial", "mundo TI", "Tecnología"],
    ratings: 4.2,
    asset: false,
  },
  {
    IdCurso: 7,
    title: "Programación avanzada en Python",
    description: "Curso avanzado de programación utilizando el lenguaje Python",
    imgCurso:
      "https://cdn.pixabay.com/photo/2017/08/05/11/16/logo-2582748_1280.png",
    idiom: "Español",
    price: 79.99,
    duration: "6 meses",
    skills: ["Python", "programación avanzada", "algoritmos"],
    difficulty: "Avanzado",
    instructor: "Juan Pérez",
    category: ["programación", "mundo TI", "Tecnología"],
    ratings: 4.8,
    asset: true,
  },
  {
    IdCurso: 8,
    title: "Diseño gráfico para principiantes",
    description: "Curso para aprender los conceptos básicos del diseño gráfico",
    imgCurso:
      "https://cdn.pixabay.com/photo/2017/08/05/11/16/logo-2582748_1280.png",
    idiom: "Español",
    price: 19.99,
    duration: "2 meses",
    skills: ["Diseño gráfico", "Adobe Illustrator", "Photoshop"],
    difficulty: "Básico",
    instructor: "Ana Torres",
    category: ["diseño gráfico", "creatividad", "arte"],
    ratings: 4.5,
    asset: false,
  },
  {
    IdCurso: 9,
    title: "Marketing digital para emprendedores",
    description:
      "Curso para emprendedores que quieren aprender a hacer marketing digital",
    imgCurso:
      "https://cdn.pixabay.com/photo/2017/08/05/11/16/logo-2582748_1280.png",
    idiom: "Español",
    price: 49.99,
    duration: "3 meses",
    skills: ["Marketing digital", "SEO", "publicidad en redes sociales"],
    difficulty: "Intermedio",
    instructor: "Luisa Ramírez",
    category: ["marketing", "negocios", "emprendimiento"],
    ratings: 4.3,
    asset: true,
  },
  {
    IdCurso: 10,
    title: "Desarrollo de aplicaciones móviles con Flutter",
    description:
      "Curso para desarrollar aplicaciones móviles utilizando el framework Flutter",
    imgCurso:
      "https://cdn.pixabay.com/photo/2017/08/05/11/16/logo-2582748_1280.png",
    idiom: "Español",
    price: 59.99,
  },
];

module.exports = cursos;
