const data = [
  {
    idData: 1,
    name: "Juan",
    lastname: "Pérez",
    correo: "juan.perez@gmail.com",
    password: "4d10e11d9b8c98c7",
    imgProfile: "https://example.com/profile-pic.jpg",
  },
  {
    idData: 2,
    name: "María",
    lastname: "González",
    correo: "maria.gonzalez@gmail.com",
    password: "a320f29eae139",
    imgProfile: "https://example.com/profile-pic-2.jpg",
  },
  {
    idData: 3,
    name: "Luis",
    lastname: "Ramírez",
    correo: "luis.ramirez@gmail.com",
    password: "30a31bcfae7",
    imgProfile: "https://example.com/profile-pic-3.jpg",
  },
  {
    idData: 4,
    name: "Ana",
    lastname: "Rodríguez",
    correo: "ana.rodriguez@gmail.com",
    password: "d9d1606bdf8f107",
    imgProfile: "https://example.com/profile-pic-4.jpg",
  },
  {
    idData: 5,
    name: "Pedro",
    lastname: "Hernández",
    correo: "pedro.hernandez@gmail.com",
    password: "f296f48a77",
    imgProfile: "https://example.com/profile-pic-5.jpg",
  },
  {
    idData: 6,
    name: "Sofía",
    lastname: "López",
    correo: "sofia.lopez@gmail.com",
    password: "a1654e4e6d",
    imgProfile: "https://example.com/profile-pic-6.jpg",
  },
  {
    idData: 7,
    name: "Jorge",
    lastname: "Martínez",
    correo: "jorge.martinez@gmail.com",
    password: "ceeb163e74d",
    imgProfile: "https://example.com/profile-pic-7.jpg",
  },
  {
    idData: 8,
    name: "Lucía",
    lastname: "García",
    correo: "lucia.garcia@gmail.com",
    password: "78a4067a1e",
    imgProfile: "https://example.com/profile-pic-8.jpg",
  },
  {
    idData: 9,
    name: "Raul",
    lastname: "Sanchez",
    correo: "raul.sanchez@gmail.com",
    password: "92d39d1bc10765a97db0",
    imgProfile: "https://example.com/profile-pic-9.jpg",
  },
  {
    idData: 10,
    name: "Carla",
    lastname: "Pérez",
    correo: "carla.perez@gmail.com",
    password: "4d9f29b8a7d20ed19b3",
    imgProfile: "https://example.com/profile-pic-10.jpg",
  },
];

module.exports = data;
