const user = [
  {
    IdUsuario: 1,
    IdDatos: 1,
    IdCursos: [10],
    IdFacturaciones: [],
    activo: true,
    IdCarrito: [],
  },
  {
    IdUsuario: 2,
    IdDatos: 2,
    IdCursos: [5, 8, 9],
    IdFacturaciones: [],
    activo: true,
    IdCarrito: [],
  },
  {
    IdUsuario: 3,
    IdDatos: 3,
    IdCursos: [],
    IdFacturaciones: [],
    activo: true,
    IdCarrito: [],
  },
  {
    IdUsuario: 4,
    IdDatos: 4,
    IdCursos: [],
    IdFacturaciones: [],
    activo: true,
    IdCarrito: [],
  },
  {
    IdUsuario: 5,
    IdDatos: 10,
    IdCursos: [2, 3],
    IdFacturaciones: [],
    activo: true,
    IdCarrito: [],
  },
  {
    IdUsuario: 6,
    IdDatos: 5,
    IdCursos: [2, 1, 5],
    IdFacturaciones: [],
    activo: true,
    IdCarrito: [],
  },
  {
    IdUsuario: 7,
    IdDatos: 6,
    IdCursos: [1],
    IdFacturaciones: [],
    activo: true,
    IdCarrito: [],
  },
  {
    IdUsuario: 8,
    IdDatos: 7,
    IdCursos: [1, 2, 3, 4, 5, 6, 7, 8],
    IdFacturaciones: [],
    activo: true,
    IdCarrito: [],
  },
  {
    IdUsuario: 9,
    IdDatos: 8,
    IdCursos: [],
    IdFacturaciones: [],
    activo: true,
    IdCarrito: [],
  },
  {
    IdUsuario: 10,
    IdDatos: 9,
    IdCursos: [10, 2, 3],
    IdFacturaciones: [],
    activo: true,
    IdCarrito: [],
  },
];

module.exports = user;
