const users = [
  {
    idUser: 1,
    name: "David",
    lastName: "Calle",
    email: "David08@gmail.com",
    password:
      "f3f9de8625da0d28e8855a4f91ed3e408b10f40670f27b25ef957dd3729b1cb4",
    imgProfile:
      "https://img-s-msn-com.akamaized.net/tenant/amp/entityid/AA17fKPH.img?w=1200&h=900&m=4&q=79",
    idCourses: [8],
    cartId: [],
    billingId: [],
    role: "buyer",
    idPosts: [],
    idCoursesSold: [],
    idComments: [],
    ratings: null,
    asset: true,
  },
  {
    idUser: 2,
    name: "Sarah",
    lastName: "Smith",
    age: 32, //!Esta propiedad es opcional y se le puede añadir a usuarios compradores.
    email: "sarahsmith@gmail.com",
    password:
      "6d34a9d6e76e4e9b7d6dca8a75d0e734c11b7cb2bf9a7eb3b94f7b89e6d5080f",
    imgProfile: "https://randomuser.me/api/portraits/women/32.jpg",
    idCourses: [1, 3],
    role: "seller",
    description:
      "Certified personal trainer with over 5 years of experience. Specializes in strength and conditioning, weight loss, and functional training.",
    studies:
      "NASM-CPT certification, TRX suspension training certification, and advanced training in functional fitness.",
    idPosts: [1, 2],
    idCoursesSold: [3],
    idComments: [4, 5],
    billingId: [123456789],
    ratings: 4.2,
    cartId: [],
    asset: true,
  },
  {
    idUser: 3,
    name: "John",
    lastName: "Doe",
    email: "johndoe@hotmail.com",
    password:
      "a04f865d14482454e0f59d00aeb5d2065e2d4b74c1a02c2d32fa40e7a83f4e61",
    imgProfile: "https://randomuser.me/api/portraits/men/12.jpg",
    idCourses: [2, 4],
    cartId: [4, 8],
    billingId: [],
    role: "buyer",
    idPosts: [],
    idCoursesSold: [],
    idComments: [],
    ratings: null,
    asset: true,
  },
  {
    idUser: 4,
    name: "Emily",
    lastName: "Jones",
    age: 28,
    email: "emilyjones@yahoo.com",
    password:
      "0e1f5c25f798a2c73d70f868d1626c4ca1b4b6c0fc93dc8a22ec2a0bc2383072",
    imgProfile: "https://randomuser.me/api/portraits/women/26.jpg",
    idCourses: [5, 3, 4],
    role: "seller",
    description:
      "Experienced nutritionist with a focus on plant-based diets and sustainable eating habits. Passionate about helping clients improve their health and well-being through healthy food choices.",
    studies:
      "Registered Dietitian (RD) certification, Plant-Based Nutrition certification from eCornell University.",
    idPosts: [4, 5],
    idCoursesSold: [3, 5],
    idComments: [1, 2, 3],
    billingId: [987654321],
    ratings: 4.9,
    cartId: [],
    asset: true,
  },
  {
    idUser: 5,
    name: "Kevin",
    lastName: "Lee",
    email: "kevinlee@gmail.com",
    password:
      "4d7a7b7b1a5fda103b1e1a18dbd65951b7ce261ae4a69a8c00b94bf3a53c0e31",
    imgProfile: "https://randomuser.me/api/portraits/men/37.jpg",
    idCourses: [1, 3, 5],
    cartId: [2, 6],
    billingId: [456789012],
    role: "buyer",
    idPosts: [],
    idCoursesSold: [],
    idComments: [],
    ratings: null,
    asset: true,
  },
  {
    idUser: 6,
    name: "Emma",
    lastName: "Bailey",
    age: 27,
    email: "emmabailey@hotmail.com",
    password:
      "74e2c6e71086277a22506fbfb1e678eae438e5cfe1a0c99b2a4a450d1ca2e9e1",
    imgProfile: "https://randomuser.me/api/portraits/women/8.jpg",
    idCourses: [8, 6],
    role: "seller",
    description:
      "Certified dance instructor with expertise in various styles including ballet, contemporary, and hip hop. Dedicated to helping students achieve their full potential through dance.",
    studies:
      "Bachelor of Fine Arts (BFA) in Dance, certification in Zena Rommett Floor-Barre technique.",
    idPosts: [15],
    idCoursesSold: [8],
    idComments: [20],
    billingId: [741852963],
    ratings: 4.6,
    cartId: [26],
    asset: true,
  },
  {
    idUser: 7,
    name: "Carlos",
    lastName: "García",
    email: "carlosgarcia@gmail.com",
    password:
      "a83d244136a03df44b11475be07e5f2d3cc8c89b829a08d9d5e236e4277437e5",
    imgProfile: "https://randomuser.me/api/portraits/men/20.jpg",
    idCourses: [2, 4],
    cartId: [3],
    billingId: [543210987],
    role: "buyer",
    idPosts: [6, 7],
    idCoursesSold: [],
    idComments: [],
    ratings: null,
    asset: true,
  },
  {
    idUser: 8,
    name: "Karen",
    lastName: "Johnson",
    email: "karenjohnson@gmail.com",
    password:
      "d01f5ee0fc42c6a6c72052b2fb44e5bae8f658e7de9fbf51cb7df15f24f1418f",
    imgProfile: "https://randomuser.me/api/portraits/women/7.jpg",
    idCourses: [3],
    cartId: [1, 5, 9],
    billingId: [],
    role: "buyer",
    idPosts: [],
    idCoursesSold: [],
    idComments: [],
    ratings: null,
    asset: true,
  },
  {
    idUser: 9,
    name: "Michael",
    lastName: "Brown",
    age: 35,
    email: "michaelbrown@yahoo.com",
    password:
      "1dd39c03d5c7dc4f8a78f08a7ce09b54ec95e7e9bbd39baf05b74832b0d1a24f",
    imgProfile: "https://randomuser.me/api/portraits/men/53.jpg",
    idCourses: [7, 10, 9, 11],
    role: "seller",
    description:
      "Experienced life coach with a passion for helping clients achieve their goals and live their best lives. Specializes in mindset and personal growth strategies.",
    studies:
      "Certified Professional Co-Active Coach (CPCC) from the Coaches Training Institute, advanced training in Neuro-Linguistic Programming (NLP).",

    idPosts: [9],
    idCoursesSold: [11, 10],
    idComments: [8, 9],
    billingId: [246801357],
    ratings: 3.7,
    cartId: [10],
    asset: true,
  },
  {
    idUser: 10,
    name: "Emma",
    lastName: "Davis",
    email: "emmadavis@hotmail.com",
    password:
      "0275a1df4b94c8f423a32d0d7ce9b261b4f7b95d5c83c6f21c2af1c4e9d3fa92",
    imgProfile: "https://randomuser.me/api/portraits/women/91.jpg",
    idCourses: [2, 5],
    cartId: [11],
    billingId: [135792468],
    role: "buyer",
    idPosts: [],
    idCoursesSold: [],
    idComments: [],
    ratings: null,
    asset: true,
  },
  {
    idUser: 11,
    name: "Julia",
    lastName: "Smith",
    age: 31,
    email: "juliasmith@gmail.com",
    password:
      "7fc200d5299055de79cb4c32842fb8b3f98a82d6dd785afeaa0e17a15bfa6e60",
    imgProfile: "https://randomuser.me/api/portraits/women/9.jpg",
    idCourses: [20, 18, 17],
    role: "seller",
    description:
      "Certified yoga instructor with a focus on stress relief and mindfulness. Believes in the healing power of yoga for both the body and mind.",
    studies:
      "200-hour RYT certification from Yoga Alliance, advanced training in Yin yoga and Yoga Nidra.",
    idPosts: [10, 11],
    idCoursesSold: [],
    idComments: [10],
    billingId: [951753684],
    ratings: 4.2,
    cartId: [12, 13],
    asset: true,
  },
  {
    idUser: 12,
    name: "Joshua",
    lastName: "Lee",
    email: "joshualee@yahoo.com",
    password:
      "6e3a4c08e85406e7d7cf0b15a5ab293a28344e11bca1155b6d64f0e3ee1f98ee",
    imgProfile: "https://randomuser.me/api/portraits/men/95.jpg",
    idCourses: [4, 5],
    cartId: [14, 15],
    billingId: [123456789],
    role: "buyer",
    idPosts: [],
    idCoursesSold: [],
    idComments: [],
    ratings: null,
    asset: true,
  },
  {
    idUser: 13,
    name: "Maria",
    lastName: "González",
    age: 29,
    email: "mariagonzalez@gmail.com",
    password:
      "cf8463e22ec9380f6f9f9ba5c46e67fda31e8dcfba66a3ef63cfc45d98b5d615",
    imgProfile: "https://randomuser.me/api/portraits/women/32.jpg",
    idCourses: [12, 13, 14, 15, 16, 21, 22],
    role: "seller",
    description:
      "Experienced martial arts instructor with expertise in Taekwondo and Muay Thai. Dedicated to helping students develop self-discipline and confidence through martial arts training.",
    studies:
      "Black belt in Taekwondo, certification in Muay Thai from the Muay Thai Institute.",
    idPosts: [],
    idCoursesSold: [13, 12, 22],
    idComments: [13],
    billingId: [789456123],
    ratings: 4.7,
    cartId: [16],
    asset: true,
  },
  {
    idUser: 14,
    name: "Jason",
    lastName: "Taylor",
    email: "jasontaylor@hotmail.com",
    password:
      "91aa5516aa3bf558f48ab8d235eb2021011cb3bb2b7b2158b788a23b60b0b7e3",
    imgProfile: "https://randomuser.me/api/portraits/men/80.jpg",
    idCourses: [1, 5],
    cartId: [17, 18, 19],
    billingId: [456789123],
    role: "buyer",
    idPosts: [],
    idCoursesSold: [],
    idComments: [],
    ratings: null,
    asset: true,
  },
  {
    idUser: 15,
    name: "Emily",
    lastName: "Davis",
    age: 26,
    email: "emilydavis@gmail.com",
    password:
      "5b5e37dbb97b42467e6d36e31f9ebbb70de9f9a8b3277f28e98bebb4c9f152c2",
    imgProfile: "https://randomuser.me/api/portraits/women/24.jpg",
    idCourses: [23, 24],
    role: "seller",
    description:
      "Certified Pilates instructor with a focus on core strength and flexibility. Passionate about helping clients improve their posture and overall health through Pilates.",
    studies:
      "Comprehensive certification in Pilates from Balanced Body University, advanced training in Pilates for special populations.",
    idPosts: [],
    idCoursesSold: [],
    idComments: [14],
    billingId: [987654321],
    ratings: 4.8,
    cartId: [],
    asset: true,
  },
  {
    idUser: 16,
    name: "Ethan",
    lastName: "Moore",
    email: "ethanmoore@yahoo.com",
    password:
      "bc1bb8f0d2c4c0f692b9cc5354b56ce130eedfcf07d691bf0f4ad14a1e8e6b39",
    imgProfile: "https://randomuser.me/api/portraits/men/14.jpg",
    idCourses: [4, 5],
    cartId: [20],
    billingId: [852963741],
    role: "buyer",
    idPosts: [],
    idCoursesSold: [],
    idComments: [],
    ratings: null,
    asset: true,
  },
  {
    idUser: 17,
    name: "Sophia",
    lastName: "García",
    age: 33,
    email: "sophiagarcia@hotmail.com",
    password:
      "f99f5cfd53e44750dcf78fba7f2dca85375c3ef6a8e7d3d8eb8a43dcda7dc9e2",
    imgProfile: "https://randomuser.me/api/portraits/women/17.jpg",
    idCourses: [25],
    role: "seller",
    description:
      "Experienced personal trainer with expertise in Olympic weightlifting and powerlifting. Dedicated to helping clients achieve their strength and fitness goals through personalized training programs.",
    studies:
      "Certified Strength and Conditioning Specialist (CSCS) from the National Strength and Conditioning Association, advanced training in Olympic weightlifting and powerlifting.",
    idPosts: [13],
    idCoursesSold: [],
    idComments: [15],
    billingId: [369852147],
    ratings: 4.5,
    cartId: [21, 22],
    asset: true,
  },
  {
    idUser: 18,
    name: "William",
    lastName: "Clark",
    email: "williamclark@gmail.com",
    password:
      "ea06f7717944d682f7368ca32c19d9d1ec1c5da04a3a0c9a8564b0a6b0c8e1b5",
    imgProfile: "https://randomuser.me/api/portraits/men/3.jpg",
    idCourses: [1, 4],
    cartId: [23],
    billingId: [654321789],
    role: "buyer",
    idPosts: [],
    idCoursesSold: [],
    idComments: [],
    ratings: null,
    asset: true,
  },
  {
    idUser: 19,
    name: "Olivia",
    lastName: "Allen",
    age: 30,
    email: "oliviaallen@gmail.com",
    password:
      "9d9fbf6d780f143c465f23c4d1e04a5a0f1fca2dfc4a271921e9d54394d285c7",
    imgProfile: "https://randomuser.me/api/portraits/women/13.jpg",
    idCourses: [26, 27, 28, 29, 30],
    role: "seller",
    description:
      "Certified nutrition coach with a focus on intuitive eating and mindful nutrition. Passionate about helping clients develop a healthy relationship with food and their bodies.",
    studies:
      "Precision Nutrition Level 1 Certification, certification in Intuitive Eating from the Intuitive Eating Institute.",
    idPosts: [14],
    idCoursesSold: [26, 27, 28, 29, 30],
    idComments: [],
    billingId: [159753246],
    ratings: 4.9,
    cartId: [],
    asset: true,
  },
  {
    idUser: 20,
    name: "Liam",
    lastName: "Roberts",
    email: "liamroberts@yahoo.com",
    password:
      "4c3d4a3e391a98ab6369e77e7a25c07c7b13d7dc33d0ef63aa1e3a52dc2383c6",
    imgProfile: "https://randomuser.me/api/portraits/men/9.jpg",
    idCourses: [2, 4],
    cartId: [24, 25],
    billingId: [852147963],
    role: "buyer",
    idPosts: [],
    idCoursesSold: [],
    idComments: [],
    ratings: null,
    asset: true,
  },
];

module.exports = users;
